### ISSUE TITLE
Launch contribution docs

### ISSUE THREAD

**Issue by schalkneethling** [mdn/mdn#127]
Launch new contribution docs

- https://github.com/mdn/mdn/pull/126

## Tasks

- [x] Complete first version of documentation
- [x] Setup redirects as appropriate in `mdn/content`
- [x] ~~Connect `mdn/mdn` to Mozilla Netlify account~~ - No longer relevant as we are service the docs from the MDN Web Docs website.
- [x] ~~Point https://mdn-contributor-docs.mozilla.org/ to the `mdn/mdn` repository on Netlify~~ - No longer relevant as we are service the docs from the MDN Web Docs website.
- [x] Redirect https://mdn-contributor-docs.mozilla.org/ to https://developer.mozilla.org/en-US/docs/MDN/Contribute
- [x] Remove meta docs from https://github.com/mdn/content/tree/main/meta
