### ISSUE TITLE
[Repo] todo-notifications

### ISSUE THREAD

**Issue by schalkneethling** [mdn/mdn#160]
- [x] triage prs
- [x] triage issues
- [ ] add contribution doc
- [x] add any notes about repo to readme
- [x] change master to main
- [x] move if necessary - create new folder - keep history https://hacks.mozilla.org/2022/08/merging-two-github-repositories-without-losing-commit-history/
- [x] update urls in content
- [x] archive repo if necessary
- [ ] add to motherboard project

**Comment by schalkneethling** [comment]
https://github.com/mdn/content/pull/21080
