### ISSUE TITLE
[CD] tracking issue for contrib docs go live 🎉

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#186]
- [ ] Set all pages to have frontmatter
- [ ] Set all urls and page titles to be consistent
- [ ] Clear out mdn/mdn
- [ ] Set up Hugo
- [ ] Add writing guide to mdn - open draft pr
- [ ] Move community docs to where they should be
  - [ ] Github page
  - [ ] figure out sidebar
  - [ ] Style
- [ ] Go through docs on mdn, move, delete, redirect each
- [ ] Go through meta docs
  - [ ] Capture any useful info
  - [ ] redirect (again)
- [ ] Remove meta docs from content
- [ ] Go through content readme and integrate into docs
  - [ ] update content readme to reflect where new docs are
