### ISSUE TITLE
[PROJECT] Remove tags from front-matter across mdn/content

### ISSUE THREAD

**Issue by hamishwillee** [mdn/mdn#262]
### Proposal

Tags in front-metadata were one, many years ago, used for generating dynamic page lists in the old wiki UI.
Currently they are used to generate sidebar icons for API state (`deprecated`, `experimental`, `non-standard`) and for sidebar organization: `Reference`, `Method`, `Property`.

However the advice for applying tags assumes that they are still used for generating page lists - it suggests adding a many reference keywords that might refer to the page as possible - including the name of the page itself. All of this information can be inferred from the page slug and is pointless.

The proposal is to completely remove all tags, replacing with specific metadata where necessary, and provide much simpler instructions for users. 

Specifically
- Remove all tags that that aren't used for any UI generation - e.g. API name, API group, likely keywords
- Replace `Reference`, `Method`, `Property`, `Type`, `Event` with page types for any pages using these for sidebar organization. (this work is already in progress for web APIs and Javascript. Needs to also happen for CSS, SVG, WebExtensions.
- Replace "state" tags  `Experimental` , `Deprecated`, `Non-standard`, `Obsolete` (may not exist) with specific metadata tags:
  ```
  status:
    - non-standard
    - deprecated
    - experimental
   ```
   Note, these default as false, and are only defined if true.
   
- Remove "Junk" & "Important' - These are used by the `SubpagesWithSummaries` macro but none of the pages with that macro have them. 
- As part of the updates any macros that use the tags should be update to not use them or use the page types.
- Contribution guidance updated.

This could be split into parts based on particular tags and/or web area - CSS, web APIs etc.

### Task list

- [x] Remove "Junk" and "Important" from pages and  `SubpagesWithSummaries` macro
- [x] Add kumascript code to support using new `status` front-matter keys by preference. 
    - [x] https://github.com/mdn/yari/issues/7799
- [x] Update page templates and contribution docs
  - [x] Web API - https://github.com/mdn/content/pull/22920 
  - [x] SVG https://github.com/mdn/content/pull/25118
  - [x] All other page-type and templates
- [x] Remove tags, replacing status tags with new `status` front-matter keys by preference. 
  - [x] web/Web API
  - [x] web/CSS
  - [x] web/Javascript
  - [x] web/html https://github.com/mdn/content/pull/24817
  - [x] web/accessibility
  - [x] web/demos https://github.com/mdn/content/pull/24818
  - [x] web/events https://github.com/mdn/content/pull/24818
  - [x] web/exslt https://github.com/mdn/content/pull/24818
  - [x] web/guide https://github.com/mdn/content/pull/24818
  - [x] web/http
    - [x] https://github.com/mdn/content/pull/25024 
    - [x] https://github.com/mdn/content/pull/25025
    - [x] https://github.com/mdn/content/pull/25026
  - [x] web/manifest https://github.com/mdn/content/pull/25027
  - [x] web/mathml - https://github.com/mdn/content/pull/25116
  - [x] web/media https://github.com/mdn/content/pull/24818
  - [x] web/opensearch - https://github.com/mdn/content/pull/25022
  - [x] web/performance https://github.com/mdn/content/pull/24818
  - [x] web/privacy https://github.com/mdn/content/pull/24818 https://github.com/mdn/content/pull/24818
  - [x] web/progressive_web_apps https://github.com/mdn/content/pull/24818
  - [x] web/security https://github.com/mdn/content/pull/24818
  - [x] web/svg - https://github.com/mdn/content/pull/25115
  - [x] web/text_fragments https://github.com/mdn/content/pull/25022
  - [x] web/tutorials https://github.com/mdn/content/pull/25022
  - [x] web/webdriver https://github.com/mdn/content/pull/25027
  - [x] web/web_components https://github.com/mdn/content/pull/25027
  - [x] web/xml
  - [x] web/xslt
  - [x] Glossary
  - [x] Learn - All done by Onkar
  - [x] Games
  - [x] MDN
  - [x] Mozilla
  - [x] Web Extensions/addons - https://github.com/mdn/content/pull/25117
  - [ ] Other (TBD)

- [x] Remove instructions for adding tags: #25131
- [ ] Remove kumascript code to support old tags
  - [ ] I.e. rendering of badges based on tags https://github.com/mdn/yari/blob/main/kumascript/src/lib/badges.ts#L39-L40 
  - [ ] Other usage of tags
  - [ ] Any assumption that tag exists in yari, even if not used.

### Additional information

These are all the places tags are used in KS: https://gist.github.com/wbamberg/1381c5c9c20752c89fed32b66c991230

We need to check whether this will cause problems for translations - I understand that translations rely on metadata from the english site, just not sure if it is Tags or all metadata.

### Are you willing to support this work?

Yes. 

### Depends on

Page types being rolled out.

**Comment by OnkarRuikar** [comment]
We can get rid of `Experimental`, `Deprecated`, `Non-standard` from front-matter all together. If it is used only by yari then yari can derive the status from BCD data directly. For more details refer https://github.com/mdn/yari/pull/7801#issuecomment-1352827751
@hamishwillee, @Rumyra , @wbamberg WDYT?

**Comment by wbamberg** [comment]
The problems with that are:
- not all MDN pages that currently have one of these tags have corresponding BCD entries (most infamously [Web API overview pages](https://github.com/mdn/content/blob/c0d1231ebfa26131a5b5f897ac9ac149891a38f8/files/en-us/web/api/media_source_extensions_api/index.md?plain=1#L8), see also https://github.com/mdn/content/discussions/4920, but probably some others)
- [some MDN pages have multiple BCD entries](https://github.com/mdn/yari/pull/7227#issuecomment-1257248189)

I think _if_ we could fix these problems it would be fine to use BCD.

**Comment by OnkarRuikar** [comment]
@wbamberg thanks for the detailed info!

There are two possible solutions here:

1. Put status only on the reference pages that have their own BCD entry.
  We shouldn't be tempted to put status everywhere guides, overviews, or mentions. It feels good at the time of writing such content. But such statuses don't get updated after. Few of them get updated in drive-by PRs (e.g. " hey! that's not experimental anymore"). Most of the readers land on the docs pages from search engines. If they end up making decisions based on stale info then it ends up being counter productive.
I think we make reference pages the single source of truth. Eventually readers will develop a habit of checking the specific pages for status. Like many devs frequently refer caniuse.com website.

2. Allow the status on any page only through `browser-compat` entry.
  Instead of manually providing status, writers will have to provide the BCD entry in front-matter.
  Cases to handle:
  a. **Pages without BCD entry** - provide BCD entry of prominent interface/feature without which the whole API overview/guide page won't exist.
  b. **Pages with multiple BCD entries** - make first entry the deciding factor for status of the whole overview page/guide. So author will have to put core interface/feature as the first entry.
  c. **Exceptions** - For rare pages that won't fit above framework, manually put status/banner by using `> ** Note/warning`. Lets not stop automation for few pages.

**Comment by wbamberg** [comment]
> @wbamberg thanks for the detailed info!
> 
> There are two possible solutions here:
> 
> 1. Put status only on the reference pages that have their own BCD entry.
> We shouldn't be tempted to put status everywhere guides, overviews, or mentions. It feels good at the time of writing such content. But such statuses don't get updated after. Few of them get updated in drive-by PRs (e.g. " hey! that's not experimental anymore"). Most of the readers land on the docs pages from search engines. If they end up making decisions based on stale info then it ends up being counter productive.
> I think we make reference pages the single source of truth. Eventually readers will develop a habit of checking the specific pages for status. Like many devs frequently refer caniuse.com website.
> 

As I said, I would be OK to disallow these features in guide pages, but from a user point of view there is a good argument that they are useful in guide pages. So I think this could go either way. But overview pages are reference pages, by any conventional definition of "reference page". Redefining them to make this problem more tractable is backwards.

Also I think it is worth asking why some content doesn't get updated properly, and whether front-matter content would be more likely to be maintained properly than in-page content. I mean, there's nothing magic about JSON that makes it better data.

> 2. Allow the status on any page only through `browser-compat` entry.
>  Instead of manually providing status, writers will have to provide the BCD entry in front-matter.
>  Cases to handle:
>  a. **Pages without BCD entry** - provide BCD entry of prominent interface/feature without which the whole API overview/guide page won't exist.

I haven't done an analysis of which pages we care about here that are missing BCD, so it's hard to tell how practical this is.

> b. **Pages with multiple BCD entries** - make first entry the deciding factor for status of the whole overview page/guide. So author will have to put core interface/feature as the first entry.

In these cases, for example, which is the "core interface":
https://developer.mozilla.org/en-US/docs/web/css/display-internal#browser_compatibility
https://developer.mozilla.org/en-US/docs/web/html/attributes/max#browser_compatibility
https://developer.mozilla.org/en-US/docs/web/css/css_conditional_rules#browser_compatibility
https://developer.mozilla.org/en-US/docs/web/css/filter_effects#browser_compatibility 
?

> c. **Exceptions** - For rare pages that won't fit above framework, manually put status/banner by using `> ** Note/warning`. Lets not stop automation for few pages.

So now we have a new way of doing things, and authors have to know about this, and when they have to use it. And we also have to keep tags for this case, so we can get this info in KumaScript?

***************

I'd love to have a single source of truth for this. I would personally prefer to use front matter than BCD, but if BCD was a good fit then it would be fine to use it. I think making it a good fit would mostly come down to:
- agreeing not to use these features in generic guide pages, and updating guide pages that are currently trying to use them
- finding a solution for API overview pages and possibly also CSS module pages, which ISTM have a totally legitimate need to use these features (as discussed in https://github.com/mdn/content/discussions/4920)
- trying to see if we can eliminate multiple BCD queries

I think there's quite a lot of work in there, and we might need different strategies in different cases. For example, the reason https://developer.mozilla.org/en-US/docs/web/html/attributes/max#browser_compatibility has multiple queries is the [weird and inconsistent way we document HTML attributes](https://github.com/openwebdocs/project/issues/114), and fixing that is quite hard IMO.

**Comment by OnkarRuikar** [comment]
> whether front-matter content would be more likely to be maintained properly than in-page content. I mean, there's nothing magic about JSON that makes it better data.

Front-matter is more structured so it's easier for yari to use and easy to automate in pr-checks/nightly fix bots.
It's not about the format but about its source. BCD repo is being maintained meticulously so we could capitalize on that.

> I would personally prefer to use front matter than BCD, but if BCD was a good fit then it would be fine to use it.

Agree. As solving these issues will make the platform more complex.

<details>
<summary>In rare case when we decide to go that far, we can consider following middle ground:</summary>
Basically we want to have flexibility to manually provide banners and tags for certain cases(CSS) and page types(API overview, guides), and for the reference pages we want yari to automatically provide banners and sidebar badges using BCD.
<pre>
How about following flow on yari side:
0 start rendering a page
1 If the content has any of the status tags, then use them. Don't refer BCD. Go to step 3.
2 Refer BCD to get the status iff `browser-compat` entry is available.
3 If the content has any of the banners then render them. Don't refer BCD. Go to step 5.
4 Refer BCD to render banners.
5 Render rest of the page, including BCD table, with current logic.
</pre>
Above strategy will solve your concerns in following way:
> agreeing not to use these features in generic guide pages

We can keep using `browser-compat` to show BCD table. As Yari will show banners, using BCD, only on api/feature ref pages. The pages will remain unchanged.

> finding a solution for API overview pages and possibly also CSS module pages, which ISTM have a totally legitimate need to use these features

We'll have to keep providing the tags and banners in content for these. Yari will not refer BCD if it sees the info in content. The pages will remain unchanged.

> trying to see if we can eliminate multiple BCD queries

In case of multiple queries. We'll have to manually provide the tags and banners in content as we are doing now.

> I think there's quite a lot of work in there, and we might need different strategies in different cases. For example, the reason [developer.mozilla.org/en-US/docs/web/html/attributes/max#browser_compatibility](https://developer.mozilla.org/en-US/docs/web/html/attributes/max#browser_compatibility) has multiple queries is the https://github.com/openwebdocs/project/issues/114, and fixing that is quite hard IMO.

With this approach such pages won't be touched. Only the ref pages where one to one mapping with BCD is available will be stripped off of tags and banners. Yari will require moderate change.

**Pros**: API Overview, CSS attributes, and guide pages will remain unchanged, and rest of the ref pages will be gradually updated to remove tags and banner macros.
**Cons**: With this we'll be keeping both the systems. And yari won't treat every page equally. :(
</details>

**Comment by hamishwillee** [comment]
I think this is done right? Closing.
