### ISSUE TITLE
[PROJECT] Asset Library

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#277]
### Proposal

It would be very useful to have a set of assets (images, audio & video files, fonts) that can be used throughout MDN. THey would be compressed and creative commons license. We've also had requests to find somewhere to store source files - ie a photoshop file that is used to create a diagram. Whilst these are different things there is no reason why they can't stay in the same _assets_ repo - as long as we are clear what are used for what.

### Task list

- [x] Create an asset repo
- [x] Source assets and add them
- [x] Create a good way to store source files (ie define file structure)
- [x] Write up instructions for adding and using files
- [ ] Publish

### Additional information

Ruth to add links to discussions about this here

**Comment by bsmth** [comment]
I don't think there's anything left to do on this one so I'm closing as done. 👍🏻
