### ISSUE TITLE
[PROJECT] Github week goals

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#279]
### Proposal

For one of the last weeks this year, the MDN content and community team are looking to do a 'github' week to focus on housekeeping before the end of the year.

This tracks the goals we would like to achieve during that week

### Task list

- [ ] Update mdn/mdn README to reflect roadmap
- [ ] Create a pinned discussion with where to go to do what (ie issue, discussion, proposal) - this could also include where to find things and policies
- [ ] Triage all repos and add template docs
- [ ] Assign tier 2 repos
- [ ] Triage mdn/content repos and pull out all content suggestions, discussions et al

**Comment by Rumyra** [comment]
- Labels
- Consistent repos
- Repo triage & discussion triage
- PR & issue guidelines
- Automation (welcome bots & workflows)
- Capture all MDN good news for the year
- Update guidelines for roadmap and where things are
