### ISSUE TITLE
todo-react

### ISSUE THREAD

**Issue by bsmth** [mdn/mdn#312]
https://github.com/mdn/todo-react

#### General

- [x] A default or custom social share image
- [x] "Preserve this repository"
- [x] "Allow squash merging" -> "Default to pull request title"
- [x] "Always suggest updating pull request branches"
- [x] "Automatically delete head branches"
- [x] Disable wiki & projects - as per repo save wiki if necessary

#### Branches

- [x] default branch is `main` (changed `master` to `main`)
- [x] Branch protection for the main branch (added):
  - [x] "Require a pull request before merging"
  - [x] "Require status checks to pass before merging"
  - [x] "Require branches to be up to date before merging"
  - [x] "Require signed commits" if appropriate

#### Actions

- [x] Welcome action
- [x] Enable CodeQL
- [x] Idle workflow
- [x] Prettier if appropriate
- [x] Editor config if appropriate
- [x] Add template docs

#### Environments, Releases, Packages

- [x] Disable environments, releases & packages if appropriate

### Issue/PR/label/discussion triage

- [x] Common set of labels
- [x] Edit existing labels as per repository
- [x] Issue templates (forms)
      https://github.com/mdn/project-template/tree/main/.github
- [x] PR template
      https://github.com/mdn/project-template/blob/main/.github/PULL_REQUEST_TEMPLATE
- [x] Triage issues, pull requests & discussion
- [x] Move all 'suggestions' to the mdn/mdn repo and add label needs triage
- [x] Remove all discussions and shut down feature (apart from mdn-community &
      translated-content)
