### ISSUE TITLE
Document Social Web Standards

### ISSUE THREAD

**Issue by schalkneethling** [mdn/mdn#331]
### Proposal

The web, particularly the social aspects of the web, is changing. New ideas and directions are being explored, and existing alternatives are adopted. At the core of this are several [open web standards](https://www.w3.org/wiki/Socialwg#Recommendations). Some of these include the following.

- [Webmention](https://www.w3.org/TR/webmention/)
- [Linked data notifications](https://www.w3.org/TR/ldn/)
- [Micropub](https://www.w3.org/TR/micropub/)
- [Activity Streams Core](https://www.w3.org/TR/activitystreams-core/)
- [Activity Streams Vocab](https://www.w3.org/TR/activitystreams-vocabulary/)
- [WebSub](https://www.w3.org/TR/websub/)
- [ActivityPub](https://www.w3.org/TR/activitypub/)

Documenting these technologies fits with our ethos of documenting open web standards and is a much better option than documenting a framework or technology that is ephemeral and already documented well by its creators and community.

These technologies are currently top of mind for many people building for the web and rethinking what social media can be. This means that by documenting these technologies, we can reach a new group of developers. This plays into our goals of making MDN Web Docs more sticky and expanding our audience.

More page views and longer time on site expand the potential of readers discovering our value-added offering (MDN Plus) and increase the chances of new signups. While these technologies are top of mind right now, like HTML, CSS, and JavaScript, they will stick around and, therefore will also ensure return visits. It, therefore, adds a long-tail effect that will benefit the project over the long term.

### Task list

- [ ] Get buy-in from stakeholders and product
- [ ] Define a roadmap for documenting topics taking into account the size of each and aligning with the interest of our readers.
- [ ] Gather interested parties inside and outside of Mozilla that want to support this work
- [ ] Start the documentation process
- [ ] Evangelize the standards we are documenting through our social channels such as Hacks, Youtube, Mastodon, Discord, Conferences
- [ ] Define a long-term plan to ensure the documentation is kept up to date. This will involve the above-interested parties and inviting subject matter experts (SMEs).

### Additional information

This conversation was seeded on the Mozilla Slack instance and this also speaks directly to Mozilla's initiative to explore this space through a Mozilla operated Mastodon instance.

- [https://mastodon.social/@mozilla](https://mastodon.social/@mozilla)
- [Mozilla to explore healthy social media alternative](https://blog.mozilla.org/en/mozilla/mozilla-launch-fediverse-instance-social-media-alternative/)

An overview of the work happening at the W3C. - https://www.w3.org/wiki/Socialwg#Recommendations

### Are you willing to support this work?

Yes

### Depends on

- Product and content team sign-off.
- Gathering support through interested parties and subject matter experts.
- Time allocated to the writer and community team to author and evangelize the work.
