### ISSUE TITLE
CSS appearance improvements

### ISSUE THREAD

**Issue by bsmth** [mdn/mdn#345]
### Proposal

We should make this page conform to other templates, fill out missing information and add some examples

__Page on MDN:__

https://developer.mozilla.org/en-US/docs/Web/CSS/appearance

### Task list

- [x] Improve layout  https://github.com/mdn/content/pull/28970
- [x] Add examples https://github.com/mdn/content/pull/28970
<strike>- [ ] Fill in missing descriptions</strike>
- [x] indicate intents for removal https://github.com/mdn/content/pull/30273

**Comment by caugner** [comment]
Probably already fixed by https://github.com/mdn/content/pull/28970.

**Comment by bsmth** [comment]
I'm going to close this one as done, with the addition of the compat data, we can make a call on freezing information added as most of these values for the vendor-prefixed version have had support removed 2+ years ago and qualify for deletion: https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Experimental_deprecated_obsolete#guidelines_for_removing_content
