### ISSUE TITLE
Media Session API

### ISSUE THREAD

**Issue by dipikabh** [mdn/mdn#347]
### Proposal

The current documentation includes:
- The landing page: https://developer.mozilla.org/en-US/docs/Web/API/Media_Session_API
- Interface pages:
  - https://developer.mozilla.org/en-US/docs/Web/API/MediaMetadata
  - https://developer.mozilla.org/en-US/docs/Web/API/MediaSession

There are a few more detailed in the spec https://w3c.github.io/mediasession/:
- MediaImage dictionary: https://developer.mozilla.org/en-US/docs/Web/API/MediaImage
- MediaPositionState dictionary
- MediaSessionActionDetails dictionary

### Task list

- [ ] Add link to MediaImage in Media Session API landing page
- [ ] Explore whether to add pages for the two dictionaries
- [ ] Research if existing pages need to be updated after comparing with spec

**Comment by Rumyra** [comment]
Can happen in triage, but noting the dictionary should be *removed* rather than added.

There is also a demo for this which wasn't encoporated into the pages at the time due to support https://github.com/mdn/dom-examples/tree/main/media-session
