### ISSUE TITLE
Chrome DevTools Protocol

### ISSUE THREAD

**Issue by CanadaHonk** [mdn/mdn#354]
### Proposal

CDP (Chrome DevTools Protocol) is a popular remote debugging protocol primarily for Chromium, but [Firefox also has an implementation](https://firefox-source-docs.mozilla.org/remote/cdp/), and [Safari seem to do as well](https://trac.webkit.org/browser/trunk/Source/JavaScriptCore/inspector/protocol). It's also [supported in NodeJS](https://chromedevtools.github.io/devtools-protocol/v8/). The Chrome DevTools team have [their own docs](https://chromedevtools.github.io/devtools-protocol/), but they are more a wider view with primarily just descriptions and types. Having some supplemental documentation detailing browser support (no existing docs exist for this afaik), and some other aspects if wanted could be good.

### Task list

- [ ] Check whether this suits MDN or should be something separate
- [ ] Gather information on what should be documented
- [ ] Create data for browser support
- [ ] Begin documentation

### Additional information

There has been *some* push to make CDP a standard[^4][^5] as well:
- [WICG repo](https://github.com/WICG/devtools-protocol)
- [RemoteDebug](https://remotedebug.org/)

### Are you willing to support this work?

Yes, I am happy to undertake and support.

**Comment by Rumyra** [comment]
Thank you for taking the time to make this suggestion @CanadaHonk !

At this time we do not think it's suitable for MDN - if in the future a dev tools protocol becomes standardised we will re-consider.
