### ISSUE TITLE
Change build process from Vue CLI to Vite create-vue 

### ISSUE THREAD

**Issue by J-Filip** [mdn/mdn#356]
### Proposal

In ["Getting started with Vue"](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_getting_started#initializing_a_new_project) the Vue CLI is used in for the "todo list" project. Vue CLI is now in maintainance mode and it's advised to use Vite to scaffold new Vue projects.

This is needed so that new users start building tools recommended from the official Vue docs,

### Task list

- [ ] remove Vue CLI and add Vite
- [ ] update the section content to be in sync with the changes on the project

### Additional information

Vue CLI - https://cli.vuejs.org/
Vite - https://vitejs.dev/
Vue docs (project scaffolding) - https://vuejs.org/guide/scaling-up/tooling.html#project-scaffolding

### Are you willing to support this work?

I can do the work but I would need support in the form of advice and reviews.

**Comment by Rumyra** [comment]
Hey @J-Filip thanks so much for your suggestion.

@chrisdavidmills is there any scope for the React docs Vite update to also include Vue?

**Comment by bsmth** [comment]
This is done in:

- [x] https://github.com/mdn/todo-vue/pull/171
- [x] https://github.com/mdn/content/pull/33167
