### ISSUE TITLE
Add `hue-interpolation-method` from Color 4

### ISSUE THREAD

**Issue by argyleink** [mdn/mdn#358]
### Proposal

`<hue-interpolation-method>` since [Color 4](https://www.w3.org/TR/css-color-4/#typedef-hue-interpolation-method) is part of gradients and [`color-mix()`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix#:~:text=%7C%0A%20%20oklch%20%20%0A%0A%3C-,hue%2Dinterpolation%2Dmethod,-%3E%20%3D%20%0A%20%20%5B%20shorter). I believe it should be added to MDN so it can be searched, understood, and connected to it's use cases 🙂 

### Task list

- [ ] Add new page for `hue-interpolation-method`
- [ ] Add an example
- [ ] Update other documentation to point to the new page

### Are you willing to support this work?

I can review for sure!

**Comment by rachelandrew** [comment]
This should likely go under https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Types#color along with the other types defined in Color 4

**Comment by Rumyra** [comment]
Thanks @argyleink - do you or @rachelandrew know if there's an intent to ship from Chrome?

**Comment by argyleink** [comment]
it's included in this one 👍🏻 https://chromestatus.com/feature/5147752829288448

**Comment by Rumyra** [comment]
Thank you @argyleink !

**Comment by bsmth** [comment]
Hi @argyleink I've [added a PR with some details](https://github.com/mdn/content/pull/25350), although I thought a `<hue>` page is appropriate instead of a dedicated page for `<hue-interpolation-method>`, what do you think?

I think the examples can be improved, the `increasing` and `decreasing` methods [are tricky to describe](https://pr25350.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/color_value/color-mix#using_hue_interpolation_methods). Describing the algos ([inc](https://www.w3.org/TR/css-color-4/#hue-increasing), [dec](https://www.w3.org/TR/css-color-4/#hue-decreasing)) as they are in the spec isn't all that helpful. If you have some idea on a better (visual?) way to improve this, I'm all ears.
