### ISSUE TITLE
Format all MDN content with Prettier

### ISSUE THREAD

**Issue by queengooborg** [mdn/mdn#362]
### Proposal

This issue is a project tracker to track the formatting of all content files using Prettier.  Going forward, we will want to use Prettier to enforce styling on content.

### Task list

- [x] Determine the best Prettier config for our needs
  - [x] bracketSameLine: true
  - [x] htmlWhitespaceSensitivity: default ("ignore" considered; https://github.com/mdn/content/pull/24081)
  - [x] trailingComma: all (Prettier v3 default)
- [x] For each grouping of files (such as by folder)...
  - [x] ...run Prettier to update the files
  - [x] ...remove grouping from .prettierignore to prevent regressions
- [x] Simplify the .prettierignore to remove the ignore of ".md"
  - [x] Reverse `.prettierignore` to become a breakdown list vs. "finished folder" list https://github.com/mdn/content/pull/24338
- [x] Enforce Prettier formatting with CI checks https://github.com/mdn/content/pull/20674
- [x] Commence the same project for translated-content https://github.com/mdn/mdn/issues/426

### Additional information

In the event of broken examples or custom formatting within codeblocks, you can do either of the following:
- Append a `-nolint` suffix to the end of the language name (for CSS, HTML, JS)
- Add a `<!-- prettier-ignore -->` above the codeblock (works for all languages)

### Related pull requests

  - [x] https://github.com/mdn/content/pull/24046
  - [x] https://github.com/mdn/content/pull/24048
  - [x] https://github.com/mdn/content/pull/24049
  - [x] https://github.com/mdn/content/pull/24050
  - [x] https://github.com/mdn/content/pull/24051
  - [x] https://github.com/mdn/content/pull/24055
  - [x] https://github.com/mdn/content/pull/24056
  - [x] https://github.com/mdn/content/pull/24057
  - [x] https://github.com/mdn/content/pull/24058
  - [x] https://github.com/mdn/content/pull/24161
  - [x] https://github.com/mdn/content/pull/24162
  - [x] https://github.com/mdn/content/pull/24062
  - [x] https://github.com/mdn/content/pull/24063
  - [x] https://github.com/mdn/content/pull/24064
  - [x] https://github.com/mdn/content/pull/24065
  - [x] https://github.com/mdn/content/pull/24197
  - [x] https://github.com/mdn/content/pull/24198
  - [x] https://github.com/mdn/content/pull/24068
  - [x] https://github.com/mdn/content/pull/24069
  - [x] https://github.com/mdn/content/pull/24070
  - [x] https://github.com/mdn/content/pull/24203
  - [x] https://github.com/mdn/content/pull/24204
  - [x] https://github.com/mdn/content/pull/24072
  - [x] https://github.com/mdn/content/pull/24073
  - [x] https://github.com/mdn/content/pull/24138
  - [x] https://github.com/mdn/content/pull/24140
  - [x] https://github.com/mdn/content/pull/24141
  - [x] https://github.com/mdn/content/pull/24142
  - [x] https://github.com/mdn/content/pull/24210
  - [x] https://github.com/mdn/content/pull/24211
  - [x] https://github.com/mdn/content/pull/24212
  - [x] https://github.com/mdn/content/pull/24214
  - [x] https://github.com/mdn/content/pull/24217
  - [x] https://github.com/mdn/content/pull/24218
  - [x] https://github.com/mdn/content/pull/24219
  - [x] https://github.com/mdn/content/pull/24221
  - [x] https://github.com/mdn/content/pull/24222
  - [x] https://github.com/mdn/content/pull/24223
  - [x] https://github.com/mdn/content/pull/24224
  - [x] https://github.com/mdn/content/pull/24225
  - [x] https://github.com/mdn/content/pull/24226
  - [x] https://github.com/mdn/content/pull/24228
  - [x] https://github.com/mdn/content/pull/24229
  - [x] https://github.com/mdn/content/pull/24230
  - [x] https://github.com/mdn/content/pull/24231
  - [x] https://github.com/mdn/content/pull/25169
  - [x] https://github.com/mdn/content/pull/26162
  - [x] https://github.com/mdn/content/pull/26697
  - [x] https://github.com/mdn/content/pull/27777
  - [x] https://github.com/mdn/content/pull/27822
  - [x] https://github.com/mdn/content/pull/27828
  - [x] https://github.com/mdn/content/pull/27830
  - [x] https://github.com/mdn/content/pull/27819
  - [x] https://github.com/mdn/content/pull/27835
  - [x] https://github.com/mdn/content/pull/27839
  - [x] https://github.com/mdn/content/pull/27840
  - [x] https://github.com/mdn/content/pull/27841
  - [x] https://github.com/mdn/content/pull/27842
  - [x] https://github.com/mdn/content/pull/27843
  - [x] https://github.com/mdn/content/pull/27844
  - [x] https://github.com/mdn/content/pull/27845
  - [x] https://github.com/mdn/content/pull/27846

### Are you willing to support this work?

Yes, I will happily lead this project as well.

**Comment by yin1999** [comment]
Hi @queengooborg, would you know how to ignore formating this line in markdown files: https://github.com/mdn/translated-content/blob/ca25ae38f6e3512efb61702b41da8c2eea8b9285/docs/zh-cn/translation-guide.md?plain=1#L136

This is a "bad-example" to compare with the previous one.

**Comment by queengooborg** [comment]
> Hi @queengooborg, would you know how to prevent from formatting this line in markdown files: https://github.com/mdn/translated-content/blob/ca25ae38f6e3512efb61702b41da8c2eea8b9285/docs/zh-cn/translation-guide.md?plain=1#L136
> 
> This is a "bad-example" to compare with the previous one.

You can use `<!-- prettier-ignore-start -->` and `<!-- prettier-ignore-end -->` to ignore a block of Markdown!

**Comment by queengooborg** [comment]
Hmm, that seems like it might be an issue with your editor.  I added those in and then ran `npx prettier -w docs/zh-cn/translation-guide.md --ignore-path ""`, and it worked just fine.  Maybe your editor is using an older version of Prettier...?

**Comment by mathewhodson** [comment]
> Hi @queengooborg, would you know how to prevent from formatting this line in markdown files: https://github.com/mdn/translated-content/blob/ca25ae38f6e3512efb61702b41da8c2eea8b9285/docs/zh-cn/translation-guide.md?plain=1#L136
> 
> This is a "bad-example" to compare with the previous one.

If it's an example, could you put it in a `md-nolint` block like this?
````
```md-nolint
- 正确：学习 Web 开发
- 错误：学习Web开发
- 正确：学习 JavaScript、HTML、CSS 等
- 错误：学习 JavaScript、 HTML、 CSS 等
- 正确：应用程序接口（API）
- 错误：应用程序接口（ API ）
```
````

**Comment by jasonren0403** [comment]
> > Hi @queengooborg, would you know how to prevent from formatting this line in markdown files: https://github.com/mdn/translated-content/blob/ca25ae38f6e3512efb61702b41da8c2eea8b9285/docs/zh-cn/translation-guide.md?plain=1#L136
> > This is a "bad-example" to compare with the previous one.
> 
> If it's an example, could you put it in a `md-nolint` block like this?
> 
> ```
> ```md-nolint
> - 正确：学习 Web 开发
> - 错误：学习Web开发
> - 正确：学习 JavaScript、HTML、CSS 等
> - 错误：学习 JavaScript、 HTML、 CSS 等
> - 正确：应用程序接口（API）
> - 错误：应用程序接口（ API ）
> ```
> ```

Not the full markdown, but only the content after colon(`：`) is to emphasized.

But we may treat them as inline code by wrapping into backticks, and that temporily solved the problem.

**Comment by queengooborg** [comment]
We are now officially complete with formatting English content!  All that remains now is the translated content!

**Comment by queengooborg** [comment]
I've created a separate project to track the translated content's Prettier formatting: https://github.com/mdn/mdn/issues/426

Now, we can mark this as complete!
