### ISSUE TITLE
Bump Node.js in all repos from v16 to v18

### ISSUE THREAD

**Issue by caugner** [mdn/mdn#370]
### Proposal

This issue is a project tracker to track the bump of Node.js from v16 to v18.

### Task list

For each non-archived repository in the mdn org that uses Node.js:

1. Update the `.github/workflows`
2. Update the `.nvmrc` (and add it, if it doesn't exist yet)
3. Update the `engines` field in the `package.json` (if it exists)

### Additional information

(none)

### Related pull requests

- [x] https://github.com/mdn/bcd-utils/pull/13
- [x] https://github.com/mdn/bob/pull/1091
- [x] https://github.com/mdn/browser-compat-data/pull/18866
- [x] https://github.com/mdn/content/pull/24308
- [x] https://github.com/mdn/interactive-examples/pull/2425
- [x] https://github.com/mdn/release-dashboard/pull/118
- [x] https://github.com/mdn/todo-vue/pull/73
- [x] https://github.com/mdn/todo-react/pull/66
- [x] https://github.com/mdn/translated-content/pull/11549
- [x] https://github.com/mdn/workflows/pull/118
- [x] https://github.com/mdn/yari/pull/8188

**Comment by queengooborg** [comment]
This has now been finished, whoo!
