### ISSUE TITLE
Merge InterfaceData.json into BCD

### ISSUE THREAD

**Issue by queengooborg** [mdn/mdn#371]
### Proposal

The [`InterfaceData.json`](https://github.com/mdn/content/blob/main/files/jsondata/InterfaceData.json) file contains data regarding the inheritance of interfaces.  However, in doing so, we are effectively keeping two separate lists of APIs: one in this file and one in BCD.  It has been [proposed long ago](https://github.com/mdn/browser-compat-data/issues/3441) that we should merge this data into BCD from when it was used in `mdn/data`, and I think that it would be useful to include in BCD.

### Task list

- [ ] Update BCD's schema to allow for an inheritance ("inh") property (note the "impl" property is always a blank array and can be removed)
- [ ] Update relevant macros to utilize BCD
- [ ] Remove `InterfaceData.json`

### Are you willing to support this work?

Yes, I will happily lead this project as well.

**Comment by Elchi3** [comment]
Hey @queengooborg, the [`InterfaceData.json`](https://github.com/mdn/content/blob/main/files/jsondata/InterfaceData.json) is updated automatically from webref. This is only a temporary hack, though. We should query webref directly without saving anything to a separate file in content or in BCD. I think it is a matter of updating the macros that consume InterfaceData.json and replace that with calls into webref directly. 
Does that make sense to you?

**Comment by Elchi3** [comment]
I think we should close this. We should get the data directly from webref and not copy anything into BCD or into content.

**Comment by caugner** [comment]
I would argue that the current approach (of automatically updating `InterfaceData.json` on a weekly basis) seems to be working fine, and has the advantage that we keep track of how the data changes (which isn't obvious with webref, because there aren't human-readable release notes of what has changed).

So I don't find it obvious that querying webref is really better.

Note that removing InterfaceData.json from content and adding similar information to BCD can be considered separately. If it makes sense to gather or query interface data in BCD, I don't see a reason not to do it. But it doesn't have to mean that we get rid of InterfaceData.json in content.

So I will go ahead and close this issue as "won't fix" for now.
