### ISSUE TITLE
[PROJECT] Define guidelines for the 'See Also' section

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#382]
### Proposal

The 'See also' section on MDN pages are inconsistent. It would be good to define a new set of guidelines.

```[tasklist]
### Tasks
- [x] Research current 'See also'
- [x] Propose new guidelines
- [x] Get feedback and integrate
- [x] Add new guidelines to writing docs
```

**Comment by Rumyra** [comment]
@dipikabh is this done? I assume so

**Comment by dipikabh** [comment]
Yes, this can be closed. Linking the PRs that were used for this work:

- [docs(meta): Add See also section guidelines to writing style guide](https://github.com/mdn/content/pull/25191)
- [docs(fix): Apply See also guidelines as examples](https://github.com/mdn/content/pull/25380)
