### ISSUE TITLE
[PROJECT] Firefox 112

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#383]
### Proposal

Project for Firefox 112 release

```[tasklist]
### Tasks
- [ ] https://github.com/mdn/content/issues/25353
- [ ] https://github.com/mdn/content/issues/25354
- [ ] https://github.com/mdn/content/issues/25355
- [ ] https://github.com/mdn/content/issues/25356
- [ ] https://github.com/mdn/content/issues/25357
- [ ] https://github.com/mdn/content/issues/25358
- [ ] https://github.com/mdn/content/issues/25359
- [ ] https://github.com/mdn/content/issues/25360
- [ ] https://github.com/mdn/content/issues/25361
- [ ] https://github.com/mdn/content/issues/25362
```
