### ISSUE TITLE
WebRTC stats - update to spec and remove dictionaries

### ISSUE THREAD

**Issue by hamishwillee** [mdn/mdn#384]
### Proposal

The WebRTC stats API documentation is out of date, and largely unusable. The proposal is to replace the existing dictionaries with up to date documentation and BCD reflecting the way this should actually be used.

The way the API works is that stats are associated with a  [RTCPeerConnection](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection). You can query for stats using three methods:
-  [`RTCPeerConnection.getStats()`](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/getStats) - query all states, or stats for a particular  "selector" (such as `inbound-rtp`)
- [RTCRtpReceiver.getStats()](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpReceiver/getStats) - query for all inbound stats.
- [RTCRtpSender.getStats()](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender/getStats) - query for all outbound stats

All of these return a [RTCStatsReport](https://developer.mozilla.org/en-US/docs/Web/API/RTCStatsReport) promise. When it resolves you can iterate the report to get an object that contains the stats for various selectors. 

The stats associated with each selector can be quite large, and can be cover a number of dictionaries in the spec. This hierarchy of dictionaries is [documented here](https://developer.mozilla.org/en-US/docs/Web/API/RTCStats#the_statistics_type_hierarchy). 

The current state is that only some of these dictionaries are documented and in BCD and that documentation is significantly out of date with the spec. 

The job would be to update [RTCStatsReport](https://developer.mozilla.org/en-US/docs/Web/API/RTCStatsReport) with information about ALL of the stats that might be returned, sorted by `selector`. 
We would also update the matching BCD - this is partially done/in discussion in https://github.com/mdn/browser-compat-data/pull/18910
Then delete all existing dictionaries, hierarchy docs, and so on.

### Task list

- [ ] BCD for [RTCStatsReport](https://developer.mozilla.org/en-US/docs/Web/API/RTCStatsReport) with all selectors and values documented:
  - started in https://github.com/mdn/browser-compat-data/pull/18910 - currently the data is in the peer connection and it needs to move to `RTCStatsReport`
  - This step is first, so we can test and verify which stats are actually implemented.
- [ ] Add docs for all items to `RTCStatsReport`
- [ ] Update [`RTCPeerConnection.getStats()`](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/getStats), [RTCRtpReceiver.getStats()](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpReceiver/getStats), [RTCRtpSender.getStats()](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender/getStats)
  - identify which stats are returned by each (for some it is obvious)
  - remove links to dictionaries and replace with link to the   `RTCStatsReport` - making clear that is where docs on the stats are.
- [RTCStats](https://developer.mozilla.org/en-US/docs/Web/API/RTCStats) - remove the hierarchy and all the linked dictionary objects
- BCD - remove all the dictionary objects

### Additional information

There are tests that can be used to verify support in different browsers for about 90% of stats, but these only work on Firefox real browsers so far. Vinyl is looking at better tests, and how we will test the remaining cases.

### Are you willing to support this work?

Yes.

### Depends on

Docs depend on being able to verify what is supported on browser platforms. BCD depends on same, but across versions.

**Comment by jan-ivar** [comment]
I'm supportive of this direction, provided it aligns with MDN policies and decisions, which I'm not familiar with.

The organization around dictionaries always seemed an implementation detail to me, confusing to web developers.

I find the https://w3c.github.io/webrtc-stats/#summary table to be the most helpful part of the spec for web developers (the RTCStatsType and Field columns), because its organization mirrors usage. E.g.:
```js
const stats = await pc.getStats();
for (const stat of stats.values()) {
  switch (stat.type) {
    case "inbound-rtp": { // <--- what you care about
      const timestamp = stat.timestamp;                    // in RTCStats dictionary
      const received = stat.packetsReceived;               // in RTCReceivedRtpStreamStats dictionary
      const lost = stat.packetsLost;                       // in RTCReceivedRtpStreamStats dictionary
      const bytes = stat.bytesReceived;                    // in RTCInboundRtpStreamStats dictionary
      const mimeType = stats.get(stat?.codecId)?.mimeType; // In RTCRtpStreamStats (xref'ing RTCCodecStats)
      break;
    }
  }
}
```
But note we'll suffer some duplication this way for members defined in inherited dictionaries. For example:
- `packetsLost` and [`packetsReceived`](https://w3c.github.io/webrtc-stats/#dom-rtcreceivedrtpstreamstats-packetsreceived) above are found under both `"inbound-rtp"` and `"remote-inbound-rtp"` stats. But judging by both spec text and when things get implemented, the two uses may benefit from separate description and BCD data.
- `codecId` is x 4.
- `timestamp` is x 16 (in the base dictionary of the [16 types](https://w3c.github.io/webrtc-stats/#dom-rtcstatstype)).

But in spite of this, it may be the way to go.

For cross references (`codecId`→`mimeType` above), linking to the referenced dictionary's type (e.g. `"codec"`) should work I think. cc @henbos in case I missed something.

**Comment by schalkneethling** [comment]
Thank you for your input @jan-ivar. I am also going to /cc @queengooborg so she is aware of this additional information.

**Comment by hamishwillee** [comment]
@jan-ivar Thanks very much. Your thinking aligns exactly with the _new_ MDN way of doing things. Previously we documented dictionaries. Now "where practical" we document the actual objects returned. The reason for this are:
- the same dictionary might be used in different APIs, and implemented at different versions in those APIs. That made recording compatibility issues near impossible.
- Working out what you got returned from an API call meant lots of jumps in the docs

Yes we are duplicating a few things. There are other WebRTC APIs where I have some concerns about this, but not this one. We don't mind a little duplication if it makes fixing the two issues above.

FWIW I also decided on this structure after discovering the summary table, and seeing the structure of the tests in http://wpt.live/webrtc/RTCPeerConnection-mandatory-getStats.https.html - it seemed to me that the spec authors understand that the dictionaries make specification easier, but comprehension harder.

**Comment by hamishwillee** [comment]
@jan-ivar The main problem we have at this point is working out versions in which things are supported. In https://github.com/mdn/browser-compat-data/pull/18910 we populated the features out of existing data in the browser compatibility dictionaries. Then we ran tests using http://wpt.live/webrtc/RTCPeerConnection-mandatory-getStats.https.html to find out what is supported in the current versions.

The problem we currently have is:
- Some dictionaries did not have compatibility info at all, or only partial
- The test http://wpt.live/webrtc/RTCPeerConnection-mandatory-getStats.https.html runs on the current firefox reliably. But it doesn't run on browserstack so we can't find the first-versions things ran on for old Firefox, Safari, Chrome.
- The test explicitly omits/notes that it can't validate support for some fields.

What we really need is a test that works back much earlier in Web RTC on all platforms
- Ideally from earliest WebRTC on all browser engines, but minimally 2 years back 
- Ideally in Browserstack, but at least within a VM.

I know @queengooborg is working on that but any hints to accelerate the process would make this all a lot easier.

**Comment by henbos** [comment]
> The organization around dictionaries always seemed an implementation detail to me, confusing to web developers.
>
> I find the https://w3c.github.io/webrtc-stats/#summary table to be the most helpful part of the spec for web developers

I agree with this, I find the hierarchy in the spec to only be confusing and making the spec less readable. The idea was not to have to define the same metrics in multiple places (e.g. there are some common ones in outbound-rtp and remote-outbound-rtp). But for many metrics like bytesSent they're actually computed differently (one is a local counter, the other comes from an RTCP packet). I would prefer we flatten the hierarchy

**Comment by LuciaWhen** [comment]
I swear on my kids and everything i love, i cried for months when these happened to me. i thought i would never be able to get my life together till i stumbled on a Twitter thread people talking about this particular Russian whom i contacted bohdanbohdan93 @ mail . Ru and it took this angelic man 48 hours to hijack my account from those cyber scammers.. its just a terrible experience i pray nobody encounters such

**Comment by hamishwillee** [comment]
BCD for this is now done!!!! See https://github.com/mdn/browser-compat-data/pull/18910 and https://developer.mozilla.org/en-US/docs/Web/API/RTCStatsReport#browser_compatibility

Docs work is in progress - see https://github.com/mdn/content/pull/26513

**Comment by hamishwillee** [comment]
There are now dictionaries for all stats objects that might be returned - as you can see there are no redlinks here: https://developer.mozilla.org/en-US/docs/Web/API/RTCStatsReport#the_statistic_types. This is the most important thing because it exposes BCD info and what is supported. 

Note however that only the new dictionaries are complete. Anything that predated this work might not includes docs for all the values. So we need to update https://developer.mozilla.org/en-US/docs/Web/API/RTCInboundRtpStreamStats to remove redlinks, and also scan through all the of the dictionaries and make sure BCD and content match.

So, "nearly done"

**Comment by hamishwillee** [comment]
Status (final checks)

- [ ] https://github.com/mdn/content/pull/36527
- [ ] RTCCertificateStats
- [ ] RTCCodecStats
- [ ] RTCDataChannelStats
- [ ] RTCInboundRtpStreamStats
- [ ] RTCIceCandidateStats
- [ ] RTCAudioSourceStats or RTCVideoSourceStats
- [ ] RTCOutboundRtpStreamStats
- [ ] RTCPeerConnectionStats
- [ ] RTCIceCandidateStats
- [ ] RTCRemoteInboundRtpStreamStats
- [ ] RTCRemoteOutboundRtpStreamStats
- [ ] RTCTransportStats
