### ISSUE TITLE
[PROJECT] Firefox release 114

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#402]
```[tasklist]
### Tasks
- [ ] https://github.com/mdn/content/issues/26684
- [ ] https://github.com/mdn/content/issues/26685
- [ ] https://github.com/mdn/content/issues/26246
- [ ] https://github.com/mdn/content/issues/26686
- [ ] https://github.com/mdn/content/issues/26687
- [ ] https://github.com/mdn/content/issues/26688
- [ ] https://github.com/mdn/content/issues/26689
- [ ] https://github.com/mdn/content/issues/26690
- [ ] https://github.com/mdn/content/issues/26691
- [ ] https://github.com/mdn/content/issues/26692
- [ ] https://github.com/mdn/content/issues/26693
- [ ] https://github.com/mdn/content/issues/26694
- [ ] https://github.com/mdn/content/issues/26695
```
