### ISSUE TITLE
Interop 2023

### ISSUE THREAD

**Issue by bsmth** [mdn/mdn#416]
We would like to improve our documentation in areas covered by Interop 2023. 

## Tasks by focus area:

The following areas need update, additions or research:

```[tasklist]
### Border-image
- [x] Blog https://developer.mozilla.org/en-US/blog/border-images-interop-2023/
```

```[tasklist]
### Color spaces and functions
- [ ] https://github.com/mdn/content/pull/30180
- [ ] https://github.com/mdn/content/pull/30074
- [ ] https://github.com/mdn/content/pull/25350
- [ ] https://github.com/mdn/content/pull/29941
- [ ] https://github.com/mdn/content/pull/26298
- [ ] https://github.com/mdn/content/pull/25135
- [ ] https://github.com/mdn/content/pull/25015
- [x] Reviews https://github.com/mdn/content/pull/26775
- [x] Reviews https://github.com/mdn/content/pull/26448
- [x] BCD https://github.com/mdn/browser-compat-data/pull/19035
- [x] BCD https://github.com/mdn/browser-compat-data/pull/19426
- [x] Blog https://developer.mozilla.org/en-US/blog/learn-css-hues-colors-hsl/
- [x] Blog https://developer.mozilla.org/en-US/blog/css-color-module-level-4/
```

```[tasklist]
### Container queries
- [ ] https://github.com/mdn/mdn/issues/256
- [ ] https://github.com/mdn/content/pull/24481
- [x] Blog https://developer.mozilla.org/en-US/blog/getting-started-with-css-container-queries/
```

```[tasklist]
### CSS Math Functions
- [ ] https://github.com/mdn/content/pull/26784
- [ ] https://github.com/mdn/browser-compat-data/pull/19882
- [ ] https://github.com/mdn/content/pull/28949
- [ ] https://github.com/mdn/content/pull/30076
- [ ] https://github.com/mdn/yari/pull/10026
```

```[tasklist]
### CSS pseudo classes
- [x] N/A pseudos that didn't make it in -> :local-link, :target-within, :past, :future, :current
- [x] audio-related (:buffering, :muted, etc.) https://github.com/mdn/content/pull/27237
- [x] :open and :closed https://github.com/mdn/content/pull/30342
- [x] :lang https://github.com/mdn/content/pull/26924
- [x] :user-valid (remove `-moz` prefix) (https://github.com/mdn/content/pull/27273)
- [x] :user-invalid (remove `-moz` prefix) (https://github.com/mdn/content/pull/27273)
- [x] :nth-col() (https://github.com/mdn/content/pull/28965)
- [x] :nth-last-col() (https://github.com/mdn/content/pull/28965)
```

```[tasklist]
### Custom properties
- [ ] https://github.com/mdn/content/pull/27902
- [ ] https://github.com/mdn/content/pull/30451
- [ ] https://github.com/mdn/content/pull/30503
```

```[tasklist]
### Flexbox
- [ ] https://github.com/mdn/content/pull/30831
- [ ] https://github.com/mdn/content/pull/30820
```

```[tasklist]
### Font Feature Detection and Palettes
- [ ] https://github.com/mdn/content/pull/27413
- [ ] https://github.com/mdn/content/pull/27513
- [x] Review: https://github.com/mdn/content/pull/28634/files
```

```[tasklist]
### Forms
- [ ] https://github.com/mdn/content/pull/30273
- [ ] https://github.com/mdn/content/pull/28970
```

```[tasklist]
### Grid
- [ ] https://github.com/mdn/content/pull/28983
- [ ] https://github.com/mdn/content/pull/27280
```

```[tasklist]
### Inert
- [ ] https://github.com/mdn/content/pull/25548
```

```[tasklist]
### Media Queries 4
- [ ] https://github.com/mdn/content/pull/27501
- [ ] https://github.com/mdn/content/pull/30925
```

```[tasklist]
### Offscreen Canvas
- [ ] https://github.com/mdn/content/pull/27563
```

```[tasklist]
### Pointer and Mouse events
- [ ] https://github.com/mdn/content/pull/27326
- [ ] https://github.com/mdn/content/pull/27466
- [ ] https://github.com/mdn/content/pull/27453
- [ ] https://github.com/mdn/content/pull/27503
```

```[tasklist]
### Scrolling
- [ ] https://github.com/mdn/content/pull/30981
- [ ] https://github.com/mdn/content/pull/25749
```

```[tasklist]
### Subgrid
- [ ] https://github.com/mdn/content/pull/28983
```

```[tasklist]
### Transforms
- [ ] https://github.com/mdn/content/pull/29313
- [ ] https://github.com/mdn/content/pull/22976
- [ ] https://github.com/mdn/mdn/issues/488
```
