### ISSUE TITLE
[PROJECT] Firefox release 116

### ISSUE THREAD

**Issue by bsmth** [mdn/mdn#422]
```[tasklist]
### Tasks
- [ ] https://github.com/mdn/content/issues/27746
- [ ] https://github.com/mdn/content/issues/27747
- [ ] https://github.com/mdn/content/issues/27748
- [ ] https://github.com/mdn/content/issues/27749
- [ ] https://github.com/mdn/content/issues/27750
- [ ] https://github.com/mdn/content/issues/27751
- [ ] https://github.com/mdn/content/issues/27756
- [ ] https://github.com/mdn/content/issues/27758
- [ ] https://github.com/mdn/content/issues/27759
- [ ] https://github.com/mdn/content/issues/27760
- [ ] https://github.com/mdn/content/issues/27174
```
