### ISSUE TITLE
Format all translated content with Prettier

### ISSUE THREAD

**Issue by queengooborg** [mdn/mdn#426]
### Proposal

This issue is a project tracker to track the formatting of all translated content files using Prettier, following https://github.com/mdn/mdn/issues/362 (for English content).  Going forward, we will want to use Prettier to enforce styling on content.

### Task list

- [ ] For each grouping of files (such as by folder)...
  - [ ] ...run Prettier to update the files
  - [ ] ...remove grouping from .prettierignore to prevent regressions
- [x] Enforce Prettier formatting with CI checks https://github.com/mdn/translated-content/pull/14195

#### Locales to Do

  - [x] es
  - [x] fr
  - [ ] ja
  - [x] ko
  - [x] pt-br
  - [x] ru
  - [x] zh-cn
  - [x] zh-tw

### Additional information

In the event of broken examples or custom formatting within codeblocks, you can do either of the following:
- Append a `-nolint` suffix to the end of the language name (for CSS, HTML, JS)
- Add a `<!-- prettier-ignore -->` above the codeblock (works for all languages)

### Are you willing to support this work?

Yes, I will happily lead this project as well.

**Comment by queengooborg** [comment]
I'm happy to say that all translated content has been formatted with Prettier now!  This project is officially complete!
