### ISSUE TITLE
[PROJECT] Firefox release 117

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#432]
```[tasklist]
### Tasks
- [ ] https://github.com/mdn/content/issues/28291
- [ ] https://github.com/mdn/content/issues/28290
- [ ] https://github.com/mdn/content/issues/28289
- [ ] https://github.com/mdn/content/issues/28287
- [ ] https://github.com/mdn/content/issues/28286
- [ ] https://github.com/mdn/content/issues/28285
- [ ] https://github.com/mdn/content/issues/28284
- [ ] https://github.com/mdn/content/issues/28283
- [ ] https://github.com/mdn/content/issues/28282
- [ ] https://github.com/mdn/content/issues/28281
- [ ] https://github.com/mdn/content/issues/28280
- [ ] https://github.com/mdn/content/issues/28279
- [ ] https://github.com/mdn/content/issues/28293
- [ ] https://github.com/mdn/content/issues/28301
- [ ] https://github.com/mdn/content/issues/28292
- [ ] https://github.com/mdn/content/issues/28294
- [ ] https://github.com/mdn/content/issues/28754
- [ ] https://github.com/mdn/content/issues/28755
- [ ] https://github.com/mdn/content/issues/28756
- [ ] https://github.com/mdn/content/issues/28758
- [ ] https://github.com/mdn/content/issues/27180
```

**Comment by dipikabh** [comment]
Removing https://github.com/mdn/content/issues/28757 from this project (see [comment](https://github.com/mdn/content/issues/28757#issuecomment-1698164241))
