### ISSUE TITLE
[PROJECT] Firefox release 118

### ISSUE THREAD

**Issue by bsmth** [mdn/mdn#441]
```[tasklist]
### Tasks
- [ ] https://github.com/mdn/content/issues/28839
- [ ] https://github.com/mdn/content/issues/28840
- [ ] https://github.com/mdn/content/issues/28841
- [ ] https://github.com/mdn/content/issues/28842
- [ ] https://github.com/mdn/content/issues/28848
- [ ] https://github.com/mdn/content/issues/28846
- [ ] https://github.com/mdn/content/issues/28845
- [ ] https://github.com/mdn/content/issues/28844
- [ ] https://github.com/mdn/content/issues/28843
- [ ] https://github.com/mdn/content/issues/28849
- [ ] https://github.com/mdn/content/issues/28850
- [ ] https://github.com/mdn/content/issues/28852
- [ ] https://github.com/mdn/content/issues/28853
- [ ] https://github.com/mdn/content/issues/28854
```

**Comment by dipikabh** [comment]
Removing https://github.com/mdn/content/issues/28838 from this FF118 project because it is still awaiting browser implementation.
This project can then be closed because all other linked tasks are complete.
