### ISSUE TITLE
Improve the explanation in `Intl.NumberFormat()` about `maximumSignificantDigits` property

### ISSUE THREAD

**Issue by Rafael-Martins** [mdn/mdn#444]
### Proposal

I think that we can add some clarification on how `maximumSignificantDigits` works, and also the relation with `roundingPriority`.

### Task list

- [ ] Reformulate docs for `maximumSignificantDigits`
- [ ] Reformulate docs for `roundingPriority`
- [ ] Reformulate docs for `maximumFractionDigits`

### Additional information

I will add more insight's about it soon as I can.

### Are you willing to support this work?

Yes
