### ISSUE TITLE
[PROJECT] Firefox release 119

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#450]
Tracking project for Firefox 119 updates

```[tasklist]
### Tasks
- [ ] https://github.com/mdn/content/issues/29299
- [ ] https://github.com/mdn/content/issues/29300
- [ ] https://github.com/mdn/content/issues/29301
- [ ] https://github.com/mdn/content/issues/29303
- [ ] https://github.com/mdn/content/issues/29306
- [ ] https://github.com/mdn/content/issues/29307
- [ ] https://github.com/mdn/content/issues/29308
- [ ] https://github.com/mdn/content/issues/29309
- [ ] https://github.com/mdn/content/issues/29310
- [ ] https://github.com/mdn/content/issues/29311
- [ ] https://github.com/mdn/content/issues/29312
```

**Comment by dipikabh** [comment]
This can be closed now because all tasks are complete.
