### ISSUE TITLE
[PROJECT] Convert JSFiddles to Live samples

### ISSUE THREAD

**Issue by caugner** [mdn/mdn#468]
### Proposal

The mdn/content embeds or links to 69 JSFiddles (*) in total, and we should convert these to live samples to make it easier to maintain them.

(*) According to `rg -i 'jsfiddle.net/[a-z0-9]' | wc -l`.

### Task list

- [ ] games/techniques/2d_collision_detection (1x)
- [ ] games/techniques/3d_on_the_web (8x)
- [ ] games/techniques/audio_for_web_games (5x)
- [ ] games/tutorials/2d_breakout_game_phaser (16x)
- [ ] games/tutorials/2d_breakout_game_pure_javascript (10x)
- [ ] web/api/datatransfer (1x)
- [ ] web/api/document (1x)
- [ ] web/api/html_drag_and_drop_api (1x)
- [ ] web/api/webgl_api/matrix_math_for_the_web (5x)
- [ ] web/api/webgl_api/webgl_best_practices (1x)
- [ ] web/api/webgl_api/webgl_model_view_projection (6x)
- [ ] web/api/xmlhttprequest (2x)
- [ ] web/css/border-radius (5x)
- [ ] web/css/css_animations (1x)
- [ ] web/css/offset-path (1x)
- [ ] web/javascript/closures (4x)

**Comment by Rumyra** [comment]
Thanks @caugner - adding it to the roadmap backlog

**Comment by bsmth** [comment]
I also looked into this recently and I'd like to share

* There 33 unique pens embedded using the `{{JSFiddleEmbed}}` macro 
* **all instances** of the `{{JSFiddleEmbed}}` macro are under `./files/en-us/games/`, specifically:
  * `games/tutorials/2d_breakout_game_phaser`
  * `games/tutorials/2d_breakout_game_pure_javascript`
  * `games/techniques/3d_on_the_web`

Here are the occurrences:

`games/tutorials/2d_breakout_game_phaser`:

```
move_the_ball/index.md:{{JSFiddleEmbed("https://jsfiddle.net/end3r/g1cfp0vv/","","400")}}
win_the_game/index.md:{{JSFiddleEmbed("https://jsfiddle.net/u8waa4Lx/1/","","400")}}
buttons/index.md:{{JSFiddleEmbed("https://jsfiddle.net/end3r/1rpj71k4/","","400")}}
bounce_off_the_walls/index.md:{{JSFiddleEmbed("https://jsfiddle.net/end3r/dcw36opz/","","400")}}
load_the_assets_and_print_them_on_screen/index.md:{{JSFiddleEmbed("https://jsfiddle.net/end3r/98xrv9x5/","","400")}}
randomizing_gameplay/index.md:{{JSFiddleEmbed("https://jsfiddle.net/end3r/3yds5ege/","","400")}}
extra_lives/index.md:{{JSFiddleEmbed("https://jsfiddle.net/end3r/yk1c5n0b/","","400")}}
scaling/index.md:{{JSFiddleEmbed("https://jsfiddle.net/end3r/6a64vecL/","","400")}}
build_the_brick_field/index.md:{{JSFiddleEmbed("https://jsfiddle.net/end3r/cck2b9e8/","","400")}}
animations_and_tweens/index.md:{{JSFiddleEmbed("https://jsfiddle.net/end3r/9o4pakrb/","","400")}}
the_score/index.md:{{JSFiddleEmbed("https://jsfiddle.net/end3r/n8o6rhrf/","","400")}}
physics/index.md:{{JSFiddleEmbed("https://jsfiddle.net/end3r/bjto9nj8/","","400")}}
game_over/index.md:{{JSFiddleEmbed("https://jsfiddle.net/end3r/436bckb7/","","400")}}
player_paddle_and_controls/index.md:{{JSFiddleEmbed("https://jsfiddle.net/end3r/ogqza0ye/","","400")}}
initialize_the_framework/index.md:{{JSFiddleEmbed("https://jsfiddle.net/end3r/h6cwzv2b/","","400")}}
collision_detection/index.md:{{JSFiddleEmbed("https://jsfiddle.net/end3r/wwneakwf/","","400")}}
```

`games/tutorials/2d_breakout_game_pure_javascript`:

```
move_the_ball/index.md:{{JSFiddleEmbed("https://jsfiddle.net/end3r/3x5foxb1/","","395")}}
mouse_controls/index.md:{{JSFiddleEmbed("https://jsfiddle.net/raymondjplante/vt7y5hcp/","","395")}}
track_the_score_and_win/index.md:{{JSFiddleEmbed("https://jsfiddle.net/raymondjplante/b3z2Lpu9/","","395")}}
bounce_off_the_walls/index.md:{{JSFiddleEmbed("https://jsfiddle.net/end3r/redj37dc/","","395")}}
create_the_canvas_and_draw_on_it/index.md:{{JSFiddleEmbed("https://jsfiddle.net/end3r/x62h15e2/","","395")}}
finishing_up/index.md:{{JSFiddleEmbed("https://jsfiddle.net/raymondjplante/dfh2tpu1/","","395")}}
paddle_and_keyboard_controls/index.md:{{JSFiddleEmbed("https://jsfiddle.net/L9xfn4up/1/","","395")}}
build_the_brick_field/index.md:{{JSFiddleEmbed("https://jsfiddle.net/raymondjplante/Lu3vtejz/","","395")}}
game_over/index.md:{{JSFiddleEmbed("https://jsfiddle.net/raymondjplante/L61c9y50/","","395")}}
collision_detection/index.md:{{JSFiddleEmbed("https://jsfiddle.net/yumetodo/kaed3hbu/","","395")}}
```

`games/techniques/3d_on_the_web`:

```
building_up_a_basic_demo_with_babylon.js/index.md:{{JSFiddleEmbed("https://jsfiddle.net/end3r/9zoeo5sy/","","350")}}
building_up_a_basic_demo_with_babylon.js/index.md:{{JSFiddleEmbed("https://jsfiddle.net/end3r/8r66fdvp/","","350")}}
building_up_a_basic_demo_with_playcanvas/engine/index.md:{{JSFiddleEmbed("https://jsfiddle.net/end3r/cqs6pg3x/","","350")}}
building_up_a_basic_demo_with_playcanvas/engine/index.md:{{JSFiddleEmbed("https://jsfiddle.net/end3r/auvcLoc4/","","350")}}
building_up_a_basic_demo_with_three.js/index.md:{{JSFiddleEmbed("https://jsfiddle.net/end3r/bwup75fa/","","350")}}
building_up_a_basic_demo_with_three.js/index.md:{{JSFiddleEmbed("https://jsfiddle.net/rybr720u/","","350")}}
building_up_a_basic_demo_with_a-frame/index.md:{{JSFiddleEmbed("https://jsfiddle.net/end3r/m85148b4/","","350")}}
building_up_a_basic_demo_with_a-frame/index.md:{{JSFiddleEmbed("https://jsfiddle.net/end3r/sq94qd6e/","","350")}}
```


__Resources and dependencies:__

In terms of moving them into regular `{{embedlivesample}}` examples, here's a list of the resources per jsfiddle:


```
https://jsfiddle.net/end3r/3x5foxb1/ - pure canvas, no deps
https://jsfiddle.net/end3r/redj37dc/ - pure canvas, no deps
https://jsfiddle.net/end3r/x62h15e2/ - pure canvas, no deps
https://jsfiddle.net/raymondjplante/Lu3vtejz/ - pure canvas, no deps
https://jsfiddle.net/raymondjplante/L61c9y50/ - pure canvas, no deps
https://jsfiddle.net/raymondjplante/dfh2tpu1/ - pure canvas, no deps
https://jsfiddle.net/raymondjplante/vt7y5hcp/ - pure canvas, no deps
https://jsfiddle.net/raymondjplante/b3z2Lpu9/ - pure canvas, no deps
https://jsfiddle.net/yumetodo/kaed3hbu/ - pure canvas, no deps
https://jsfiddle.net/L9xfn4up/1/ - pure canvas, no deps

https://jsfiddle.net/end3r/9zoeo5sy/ - Babylon.js dep
https://jsfiddle.net/end3r/8r66fdvp/ - Babylon.js dep
https://jsfiddle.net/end3r/cqs6pg3x/ - playcanvas-latest.js dep
https://jsfiddle.net/end3r/auvcLoc4/ - playcanvas-latest.js dep
https://jsfiddle.net/end3r/bwup75fa/ - three.min.js dep (BROKEN)
https://jsfiddle.net/end3r/m85148b4/ - aframe.min.js (has console warn/err)
https://jsfiddle.net/end3r/sq94qd6e/ - aframe.min.js (has console warn/err)

https://jsfiddle.net/end3r/h6cwzv2b/ - Phaser dep
https://jsfiddle.net/end3r/6a64vecL/ - Phaser dep
https://jsfiddle.net/end3r/dcw36opz/ - Phaser dep, one image (img/ball.png)
https://jsfiddle.net/end3r/98xrv9x5/ - Phaser dep, one image (img/ball.png)
https://jsfiddle.net/end3r/g1cfp0vv/ - Phaser dep, one image (img/ball.png)
https://jsfiddle.net/end3r/bjto9nj8/ - Phaser dep, one image (img/ball.png)
https://jsfiddle.net/end3r/cck2b9e8/ - Phaser dep, several small images
https://jsfiddle.net/end3r/9o4pakrb/ - Phaser dep, several small images
https://jsfiddle.net/end3r/n8o6rhrf/ - Phaser dep, several small images
https://jsfiddle.net/end3r/436bckb7/ - Phaser dep, several small images
https://jsfiddle.net/end3r/ogqza0ye/ - Phaser dep, several small images
https://jsfiddle.net/end3r/wwneakwf/ - Phaser dep, several small images
https://jsfiddle.net/end3r/3yds5ege/ - Phaser dep, several small images
https://jsfiddle.net/end3r/yk1c5n0b/ - Phaser dep, several small images
https://jsfiddle.net/end3r/1rpj71k4/ - Phaser dep, several small images
https://jsfiddle.net/u8waa4Lx/1/ - Phaser dep, several small images
```


There are 23 with dependencies so we would need to figure out how to include / load:

* http://phaser.io/ (Phaser v2.4.2)
* https://www.babylonjs.com/ 
* https://github.com/mrdoob/three.js/
* https://aframe.io/docs/1.5.0/introduction/ 

Plus some small images which can live beside the documents, possibly.

**Comment by bsmth** [comment]
Here's a PR to add the vanilla JS fiddles:

- [ ] https://github.com/mdn/content/pull/32258

**Comment by Josh-Cena** [comment]
Please see also https://github.com/mdn/content/issues/16120 for a up-to-date and complete list
