### ISSUE TITLE
Add LBRY scheme to allowlist documentation

### ISSUE THREAD

**Issue by ben221199** [mdn/mdn#472]
### Proposal

Add the `lbry` protocol scheme to the allowlist for registering protocol handlers.

### Task list

- [ ] Implement `lbry` in browsers.
- [ ] Merge the WHATWG pull request.
- [ ] Merge the MDN pull request.

### Are you willing to support this work?

Yes

**Comment by pepelsbey** [comment]
Hello! It’s a placeholder issue, as far as I see. There’s nothing to do on the MDN side before it becomes a part of the Web platform. Let’s get back to it once we have a browser implementation.

**Comment by Rumyra** [comment]
As this does not have the required browser interest I'll be closing this issue
