### ISSUE TITLE
[PROJECT]: Modernize React tutorials

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/mdn#474]
The MDN Learning area [React tutorials](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_getting_started) are a few years old now and need updating. In general:

1. We want to update them to use [Vite](https://vitejs.dev/), as [create-react-app](https://create-react-app.dev/) is long in the tooth now. Even the new React team tutorials don't use it anymore.
2. They need general modernization, to check that everything still works and is best practice.

We have contracted @mxmason, the writer of the original tutorials, to do this. @chrisdavidmills will act as a reviewer for this project.

## Task list

- [x] Update [Introduction to client-side frameworks](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Introduction)
- [x] Update [Framework main features](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Main_features)
- [x] Update [Getting started with React](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_getting_started)
- [x] Update [Beginning our React todo list](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_todo_list_beginning)
- [x] Update [Componentizing our React app](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_components)
- [x] Update [React interactivity: Events and state](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_interactivity_events_state)
- [x] Update [React interactivity: Editing, filtering, conditional rendering](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_interactivity_filtering_conditional_rendering)
- [x] Update [Accessibility in React](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_accessibility)
- [x] Update [React resources](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_resources)
- [x] Update the https://github.com/mdn/todo-react repo with the latest state of the todo app

## Related PRs

- https://github.com/mdn/content/pull/30515
- https://github.com/mdn/content/pull/30177
- https://github.com/mdn/content/pull/30453
- https://github.com/mdn/content/pull/30514
- https://github.com/mdn/content/pull/30977
- https://github.com/mdn/content/pull/31093
- https://github.com/mdn/content/pull/31139

**Comment by Rumyra** [comment]
Thanks @chrisdavidmills ❤️
