### ISSUE TITLE
Add new "mode" option to FileSystemAccessFileHandle's createSyncAccessHandle and createWritable

### ISSUE THREAD

**Issue by nathanmemmott** [mdn/mdn#479]
### Proposal

As part of the [New Locking Scheme to Enable Multiple Readers and Writers](https://github.com/whatwg/fs/blob/main/proposals/MultipleReadersWriters.md#new-locking-scheme-to-enable-multiple-readers-and-writers), a new "mode" option is added to both FileSystemAccessFileHandle's createSyncAccessHandle and createWritable functions.

### Browser support

Chrome
* Bug: https://crbug.com/1382215
* Feature status: https://chromestatus.com/feature/5172892632875008
  * Shipping M121

### Tasks

- [createSyncAccessHandle() method](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileHandle/createSyncAccessHandle)
  - [ ]  Add "options" (FileSystemCreateSyncAccessHandleOptions dictionary) to Parameters
  - [ ]  Describe the "mode" property, it's possible values ("readwrite", "readonly", "readwrite-unsafe"), and its default value ("readwrite").
- [createWritable() method](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileHandle/createWritable)
  - [ ] Add the "mode" property to "options".
  - [ ] Describe it, its possible values ("siloed", "exclusive"), and its default value ("siloed").

### Dependencies

- [x] Feature needs to be shipped in Chrome (https://chromestatus.com/feature/5172892632875008)

### Are you willing to support this work?

Can support with reviews and feedback.

**Comment by Rumyra** [comment]
@chrisdavidmills are you handling this? If so let me know otherwise I'll add to our team tasks

**Comment by chrisdavidmills** [comment]
@Rumyra I'm happy to do this; I'll add it to my worklist. 

Proposal makes sense and looks pretty solid; ideally we should wait until its actually in the spec before documenting. I'll keep an eye on https://github.com/whatwg/fs/pull/151 for progress on this.

**Comment by nathanmemmott** [comment]
The feature will be shipped in Chrome stable on Tue, Jan 23, 2024.

**Comment by chrisdavidmills** [comment]
@nathanmemmott I've added docs to cover these features: https://github.com/mdn/content/pull/35334. Would you be able to provide me with a tech review of this work, or is there someone more appropriate to ask?

Also pinging @tomayac as I know he is heavily involved with APIs around this area.

**Comment by nathanmemmott** [comment]
Left a few comments on the PR. Looks good!

**Comment by chrisdavidmills** [comment]
Great stuff, thanks @tomayac and @nathanmemmott!

**Comment by chrisdavidmills** [comment]
Ooop, this was fixed by https://github.com/mdn/content/pull/35334

**Comment by chrisdavidmills** [comment]
@Rumyra can you close it for me? I don't have the privs.
