### ISSUE TITLE
[PROJECT] Firefox 121

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#481]
Tracking project for Firefox 121 release updates

```[tasklist]
### Tasks
- [ ] https://github.com/mdn/content/issues/30333
- [ ] https://github.com/mdn/content/issues/30334
- [ ] https://github.com/mdn/content/issues/30335
- [ ] https://github.com/mdn/content/issues/30336
- [ ] https://github.com/mdn/content/issues/30337
- [ ] https://github.com/mdn/content/issues/30338
- [ ] https://github.com/mdn/content/issues/30339
- [ ] https://github.com/mdn/content/issues/30340
```

**Comment by bsmth** [comment]
Closing as done now 🎉
