### ISSUE TITLE
Document the `navigation.activation` APII

### ISSUE THREAD

**Issue by noamr** [mdn/mdn#491]
### Proposal

NavigationActivation is a new API, part of the navigation API, that exposes information about the most recent *activation* (cross-document navigation): the old URL, new URL and navigation type.

See [HTML PR](https://github.com/whatwg/html/pull/9856) for details.

### Browser support

Supported behind a flag in Chromium, opening this feature request in advance

### Tasks

- [ ] Document the new `NavigationActivation` interface
- [ ] Link to it from the navigation API docs
- [ ] Explain how it works in tandem with view transitions

### Dependencies

- [ ]

**Comment by bsmth** [comment]
Thanks a lot for opening this one. I'm pasting in details from your linked issue for convenience:

> * [x]  Implementation bugs are filed:
>  * Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1492932
>  * Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1777171 (main navigation API bug)
>  * WebKit: https://bugs.webkit.org/show_bug.cgi?id=258384 (main navigation API bug)

**Comment by skyclouds2001** [comment]
some done in https://github.com/mdn/content/pull/34118, other done in https://github.com/mdn/content/pull/36442
