### ISSUE TITLE
[PROJECT] Firefox 122

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#496]
Firefox 122 project
Due Date: [January 23, 2024](https://whattrainisitnow.com/calendar/#Future_branch_dates)

```[tasklist]
### Tasks
- [ ] https://github.com/mdn/content/issues/31102
- [ ] https://github.com/mdn/content/issues/31108
- [ ] https://github.com/mdn/content/issues/31103
- [ ] https://github.com/mdn/content/issues/31109
- [ ] https://github.com/mdn/content/issues/31104
- [ ] https://github.com/mdn/content/issues/31105
- [ ] https://github.com/mdn/content/issues/31110
- [ ] https://github.com/mdn/content/issues/31114
- [ ] https://github.com/mdn/content/issues/31098
- [ ] https://github.com/mdn/content/issues/31099
- [ ] https://github.com/mdn/content/issues/31100
- [ ] https://github.com/mdn/content/issues/31101
- [ ] https://github.com/mdn/content/issues/31106
- [ ] https://github.com/mdn/content/issues/31107
- [ ] https://github.com/mdn/content/issues/31111
- [ ] https://github.com/mdn/content/issues/31112
- [ ] https://github.com/mdn/content/issues/31113
```
