### ISSUE TITLE
Federated Credential Management API | sync

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/mdn#501]
### Proposal

Chrome 120 supports various [Fed CM API](https://developer.mozilla.org/en-US/docs/Web/API/FedCM_API) extensions - which called as Login Status API

### Browser support

Chrome&Edge 120 & Opera 106

### Tasks

- [ ] add documentation
  - [ ] add `Navigator.login` property page (also update properties list in `Navigator` interface page)
  - [ ] add `NavigatorLogin` interface page
  - [ ] add `NavigatorLogin.setStatus()` method page
  - [ ] add `IdentityProvider.close()` static method page (also update methods list in `IdentityProvider` interface page)
  - [ ] update GroupData
- [ ] update BCD to add mdn_url

### Additional information

spec - https://fedidcg.github.io/FedCM/

chrome status - https://chromestatus.com/feature/5177628008382464

BCD data pull request - https://github.com/mdn/browser-compat-data/pull/21721

**Comment by chrisdavidmills** [comment]
I'm about to do this, so this can be assigned to me.

**Comment by Rumyra** [comment]
Thanks so much @skyclouds2001 & @chrisdavidmills - assigned and added to roadmap

**Comment by skyclouds2001** [comment]
close as https://github.com/mdn/content/pull/31658 has been merged
