### ISSUE TITLE
Javascript error reference is incomplete

### ISSUE THREAD

**Issue by nataliaschlebinger** [mdn/mdn#505]
### Proposal

Hi! Looking through the error definitions in V8 and SpiderMonkey, I found errors that I couldn't find in the reference, and I think there could be a lot of them. Here are some examples:

| Code | Error (SpiderMonkey) |
| ---------|---------- |
| `Atomics.and()` | `TypeError: invalid array type for the operation`
| `class {}` | `SyntaxError: class statement requires a name`
| `(new WeakMap()).set('mykey', 1)` | `TypeError: WeakMap key "mykey" must be an object or an unregistered symbol`
| `Promise()` | `TypeError: calling a builtin Promise constructor without new is forbidden`
| `new Map([1,2])` | `TypeError: iterable for Map should have array-like object`
| `(class MyClass{})()` | `TypeError: class constructors must be invoked with 'new'`
| ``` `${``; ``` | `SyntaxError: missing } in template string`
|`/)/;` | `SyntaxError: unmatched ) in regular expression` 
| `Number({[Symbol.toPrimitive]: 1})` | `TypeError: can't convert ({[Symbol.toPrimitive]:1}) to number: its [Symbol.toPrimitive] property is not a function`
| `function test(...params, other){}` | `SyntaxError: parameter after rest parameter`
| `({set prop(){}})` | `SyntaxError: setter functions must have one argument`

One problem is that a lot of the errors in the engine's code I've looked at are not user facing, so I don't know how to give a definitive "this error is NEVER gonna appear in a web application", only "this error WILL appear, here's a code sample that throws it". The method I've been using to find undocumented errors is understanding or googling them and manually checking if I can cause them.

Maybe a good idea would be to keep a list of our progress through the engine's error definitions, or at least a list of the new errors we have found. If we base ourselves in an engine, we should agree which engine. Maybe SpiderMonkey would be a good choice.

Right now the Firefox's web console shows some JS errors with a link to their corresponding MDN docs article. After we document the new errors I'm proposing, we should probably notify the Firefox folks about it.

### Browser support

Yes, I've checked in Firefox 120.0 and Google Chrome 120.0.6099.129

### Tasks

- [ ] Look through error message definitions in a Javascript engine for user facing errors, modifying list/s to reflect our progress.
- [ ] Add a new article to the error reference  for each undocumented error.
- [ ] Talk to the Firefox folks, to link the new docs in the Web Console errors.

### Dependencies

None

### Additional information

Here are some files I think we should be looking at:

- [SpiderMonkey error messages](https://github.com/mozilla/gecko-dev/blob/master/js/public/friend/ErrorNumbers.msg)
- [V8 error messages](https://github.com/v8/v8/blob/master/src/common/message-template.h)
- [Where I think Firefox maps erros to doc links](https://github.com/mozilla/gecko-dev/blob/master/devtools/server/actors/errordocs.js)

### Are you willing to support this work?

I can and want to support this work, with writing, reviews and feedback.

**Comment by nataliaschlebinger** [comment]
Hi @Rumyra! Me and Brian have been talking about this issue, and we thought that maybe we could have discussing it on the agenda for the next community call?

**Comment by bsmth** [comment]
We'll put it on here (I can put it on the agenda) https://github.com/mdn/community-meetings/blob/main/24-01-22/agenda.md

**Comment by Josh-Cena** [comment]
FWIW, I've tried to automate this using my ES spec scraper, but it has been largely stalled. Some problems:

1. If an Abstract Operation throws an error, the actual error message may differ depending on what calls that AO. (I think this is not very common, though)
2. Multiple places that throw an error may use the same error message (particularly for input type validation).
3. The error-throwing conditions are hard to statically extract; currently I've just focused on early errors and it's already a mouthful. Look at https://www.unpkg.com/es-scraper/generated/early-errors.json
4. I'm not even sure if we want to be totally exhaustive with this section. It's a huge maintenance hassle and impossible to be kept up to date with every new feature.

**Comment by nataliaschlebinger** [comment]
Hi Josh! Thank you for your time!

I would like to define being exhaustive with the error reference, for the purpose of this issue, as having all the lines on the sheet I edited on the issue, with a checkbox marked. That would be all the lines in the V8 file where most or all of the error messages seem to be, although I can't be sure if there might be more error messages elsewhere. After doing that I think the issue should definitely be closed.

About the motivation, I googled a little, and I'm also doubting it should be exhaustive, but I'm also doubting if it would be better to decide what not to document. I definitely think some error messages are missing, like for instance there is only one documented about classes. What criteria could we use if we don't wanna include all the messages? In favor of just including them all, I can think of the cost of having to make the decision for each one, that the page structure for the error reference wouldn't change much if we documented them all, and that maybe it would be nice if Firefox included a "learn more" link to the docs for all the errors (running `function(){};` would be an example of this).

About keeping up with new features, I think it's doable, since we would only need to keep up with new Javascript, and the error cases for it will be on the spec. And for keeping up with the browsers, I don't know if there are automated tests for the docs? These pages are definitely testable, one way is running the example from the page on a (headless?) browser and check that the error message corresponds to the one listed on the page.

I agree the error cases are hard to statically extract, and I would love to have a way to list them. Still, a human would have to put of their thinking for either each error case or error message in order to document it, so I don't think that the tradeoff of waiting until there is a full list to start completing the error reference is worth it.

**Comment by nataliaschlebinger** [comment]
Alright! As discussed on Discord and the community call, I edited from "Look at (preferably the next) line with no checkbox" to "Look at a very interesting line with no checkbox". Also, @Elchi3 it was discussed you might be interested in seeing this initiative 😃 !

**Comment by Josh-Cena** [comment]
I've made a similar spreadsheet, based on Gecko errors: https://docs.google.com/spreadsheets/d/1BQRLHhNXvrTNKf6YkxdHVJ5eSjt9gM5-otmX9_jMKKM/edit?usp=sharing

**Comment by Josh-Cena** [comment]
Btw, the V8 messages are incomplete, because you are looking at the `master` branch, but you need to look at the [`main` branch](https://github.com/v8/v8/blob/main/src/common/message-template.h) instead.

**Comment by nataliaschlebinger** [comment]
Hi! Wow, what amazing work I see here!! Would you like me to edit the issue and replace the V8 message sheet with the SpiderMonkey one? I've requested access to take a look, but also I gotta say the V8 message sheet is looking amazing and revamped!! Maybe I could edit the issue to add the workflow for it? What would be the new workflow?

Also great catch about the V8 message spreadsheet!

And also sorry I needed to stay away from this initiative for quite some weeks, this week I'm getting back on track. Thank you for this quality and volume of work!!!

**Comment by Josh-Cena** [comment]
> Would you like me to edit the issue and replace the V8 message sheet with the SpiderMonkey one?

Shared! I think it's valuable to track both in the issue. Granted, our error reference pages are keyed by FF errors so if FF gives the same error message for 10 V8 errors we would probably still document on the same page. But I think the V8 table is still good as a way to discover more error conditions.

> Maybe I could edit the issue to add the workflow for it? What would be the new workflow?

I think you would put "claimed" in the "PR" column and then update that with the PR link once you send the PR. No strong feelings though, you can also add it as a new status in the status column.

> And also sorry I needed to stay away from this initiative for quite some weeks, this week I'm getting back on track. Thank you for this quality and volume of work!!!

No worries! Take your time as this is going to be a year-round effort anyway. I've been thinking about it for a while but just never got to it.

**Comment by Josh-Cena** [comment]
As a status update: I'm sending a few patches to Firefox to improve the error messages before I document them.

**Comment by Josh-Cena** [comment]
Hmmm, I just realized we have a page at https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Document_web_errors. We need to get it updated afterwards.
