### ISSUE TITLE
Add documentation for JS Self-Profiling API | Or combine it with current Performance APIs

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/mdn#507]
### Proposal

the spec https://wicg.github.io/js-self-profiling/, the feature is at least supported by Chrome

since it is relates with performance, I guess it is a good idea to combine it with current *Performance APIs*

### Tasks

- [ ] add documentation for the API
  - [ ] update Performace API landing page
  - [ ] add Performace API guide page fot this API
  - [ ] document the `Profiler` interface and its members
  - [ ] update GroupData in Performace APIs
- [ ] update BCD to add mdn_url

**Comment by Rumyra** [comment]
Thanks @skyclouds2001 - again I can see this in your backlog @chrisdavidmills so assigning 👍

**Comment by skyclouds2001** [comment]
see also https://github.com/mdn/mdn/issues/610

**Comment by wbamberg** [comment]
Thank you @skyclouds2001 ! I'm currently working on this.

**Comment by bsmth** [comment]
From @captainbrosset in the closed issue:

> The JS Self-Profiling API's draft spec is here: https://wicg.github.io/js-self-profiling/ This API can be used by web developers to perform profiling, at runtime, to gain performance insights about their production webapps.
> 
> The feature is already known to BCD, see https://github.com/mdn/browser-compat-data/blob/main/api/Profiler.json
> ### Browser support
> 
> Supported on Chrome, Chrome Android, and Edge, since version 94. See https://web-platform-dx.github.io/web-features-explorer/features/profiler/


Heads-up @chrisdavidmills -> @wbamberg is currently working on this

**Comment by skyclouds2001** [comment]
see https://github.com/mdn/content/pull/37796
