### ISSUE TITLE
Add docs for Private State Token API

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/mdn#510]
### Proposal

the feature has been supported since Chrome 117, see BCD update

### Browser support

Chrome 117 + (and Edge)

### Tasks

- [ ] BCD add
  - [ ] `Document.hasPrivateTokens()`
  - [ ] `<iframe>` element `privateToken` attribute
  - [ ] `Sec-Private-State-Token` HTTP header
  - [ ] `Sec-Private-State-Token-Lifetime` HTTP header
  - [ ] `Sec-Private-State-Token-Crypto-Version` HTTP header
  - [ ] `Sec-Redemption-Record` HTTP header
- [ ] document add
  - [ ] API summary documentation
  - [ ] add API guide documentation (if needed)
  - [ ] `HTMLIFrameElement.privateToken` (update `HTMLIFrameElement` list)
  - [ ] `XMLHttpRequest.setPrivateToken()` (update `XMLHttpRequest` list)
  - [ ] `Request` constructor `privateToken` option
  - [ ] `fetch()` method `privateToken` option
  - [ ] `Document.hasPrivateTokens()` (update `Document` list)
  - [ ] `Document.hasRedemptionRecord()` (update `Document` list)
  - [ ] `<iframe>` element `privateToken` attribute
  - [ ] `Sec-Private-State-Token` HTTP header
  - [ ] `Sec-Private-State-Token-Lifetime` HTTP header
  - [ ] `Sec-Private-State-Token-Crypto-Version` HTTP header
  - [ ] `Sec-Redemption-Record` HTTP header
- [ ] update BCD to add mdn_url

### Additional information

spec https://wicg.github.io/trust-token-api/

**Comment by Rumyra** [comment]
Thanks @skyclouds2001 :) 

@chrisdavidmills I can see this in your backlog so assigning to you - @skyclouds2001 has written up a great checklist of the tasks above ☝️

**Comment by chrisdavidmills** [comment]
Great stuff, thanks both. I'll make sure to reference this issue when I work on this.

**Comment by chrisdavidmills** [comment]
This got done: https://developer.mozilla.org/en-US/docs/Web/API/Private_State_Token_API

**Comment by Rumyra** [comment]
Thanks @chrisdavidmills
