### ISSUE TITLE
Add docs for Attribution Reporting API

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/mdn#513]
### Proposal

the Attribution Reporting API allows to report that an event may have been caused by another cross-site event. These reports are designed to transfer little enough data between sites that the sites can’t use them to track individual users.

### Browser support

supported by Chrome 117+

### Tasks

- [ ] update docs
  - [ ] add docs for API summary page
  - [ ] add docs for guide page (I think this may not be required)
  - [ ] add docs for `HTMLAnchorElement.attributionSrc` (also update properties list for `HTMLAnchorElement`)
  - [ ] add docs for `HTMLImageElement.attributionSrc` (also update properties list for `HTMLImageElement`)
  - [ ] add docs for `HTMLScriptElement.attributionSrc` (also update properties list for `HTMLScriptElement`)
  - [ ] update `Request()` constructor `init` parameter `attributionReporting` option
  - [ ] update `fetch()` method `init` parameter `attributionReporting` option
  - [ ] add docs for `XMLHttpRequest.setAttributionReporting()` (also update methods list for `XMLHttpRequest`)
  - [ ] update `Window.open()` `features` option
  - [ ] update attributes list for `<a>`
  - [ ] update attributes list for `<img>`
  - [ ] update atributes list for `<script>`
  - [ ] add docs for `Attribution-Reporting-Eligible` HTTP header
  - [ ] add docs for `Attribution-Reporting-Register-Source` HTTP header
  - [ ] add docs for `Attribution-Reporting-Register-Trigger` HTTP header
  - [ ] add docs for `Attribution-Reporting-Support` HTTP header
  - [ ] add docs for `attribution-reporting` `Permission-Policy` directive (also update directives list in `Permission-Policy` http)
- [ ] add the API to GroupData
- [ ] update BCD data with mdn_url

### Additional information

the spec documentation https://wicg.github.io/attribution-reporting-api/

BCD data update https://github.com/mdn/browser-compat-data/pull/20460/

**Comment by skyclouds2001** [comment]
has been working on in https://github.com/mdn/content/pull/28471

**Comment by skyclouds2001** [comment]
has been working on in https://github.com/mdn/content/pull/28471
