### ISSUE TITLE
[PROJECT] Firefox 123

### ISSUE THREAD

**Issue by pepelsbey** [mdn/mdn#519]
Firefox 123 project
Due Date: [February 20, 2024](https://whattrainisitnow.com/calendar/#Future_branch_dates)

```[tasklist]
### Tasks
- [ ] https://github.com/mdn/content/issues/31863
- [ ] https://github.com/mdn/content/issues/31914
- [ ] https://github.com/mdn/content/issues/31865
- [ ] https://github.com/mdn/content/issues/31912
- [ ] https://github.com/mdn/content/issues/31915
- [ ] https://github.com/mdn/content/issues/31913
- [ ] https://github.com/mdn/content/issues/31890
- [ ] https://github.com/mdn/content/issues/31889
```
