### ISSUE TITLE
Bump Node.js in all repos from v18 to v20

### ISSUE THREAD

**Issue by caugner** [mdn/mdn#521]
> [!IMPORTANT]  
> This is a draft project, please do not start working on this yet.

### Proposal

This issue is a project tracker to track the bump of Node.js from v18 to v20.

### Task list

For each non-archived repository in the mdn org that uses Node.js:

1. Update the `.nvmrc` file.
2. Update the `.github/workflows` files to use `node-version-file: '.nvmrc'`
3. Update the `engines` field in the `package.json` (if it exists)

### Additional information

(none)

### Related pull requests

- [x] mdn/bcd-utils: https://github.com/mdn/bcd-utils/pull/120
- [x] mdn/bob: https://github.com/mdn/bob/pull/2042
- [x] mdn/browser-compat-data: https://github.com/mdn/browser-compat-data/pull/24964
- [x] mdn/content: https://github.com/mdn/content/pull/36675
- [x] mdn/interactive-examples: https://github.com/mdn/interactive-examples/pull/2859
- [x] mdn/mdn-http-observatory
- [ ] mdn/release-dashboard: https://github.com/mdn/release-dashboard/issues/358
- [x] mdn/todo-vue (was already on v20 since https://github.com/mdn/todo-vue/pull/171)
- [ ] mdn/todo-react: https://github.com/mdn/todo-react/issues/224
- [x] mdn/translated-content: https://github.com/mdn/translated-content/pull/24375
- [x] mdn/workflows: https://github.com/mdn/workflows/pull/149
- [x] mdn/yari: https://github.com/mdn/yari/pull/12052

**Comment by caugner** [comment]
I have bumped Node.js wherever possible, and there are specific issues for where it wasn't possible:

- https://github.com/mdn/release-dashboard/issues/358
- https://github.com/mdn/todo-react/issues/224
