### ISSUE TITLE
[PROJECT] Firefox release 124

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#526]
Project tracking issue for FF124

```[tasklist]
### Tasks
- [ ] https://github.com/mdn/content/issues/32342
- [ ] https://github.com/mdn/content/issues/32341
- [ ] https://github.com/mdn/content/issues/32340
- [ ] https://github.com/mdn/content/issues/32339
- [ ] https://github.com/mdn/content/issues/32338
- [ ] https://github.com/mdn/content/issues/32337
```
