### ISSUE TITLE
Add docs for service worker static routing API

### ISSUE THREAD

**Issue by sisidovski** [mdn/mdn#527]
### Proposal

Service worker static routing API is the newly introduced API. This API allows developers to configure the routing, and allows them to offload simple things ServiceWorkers do. If the condition matches, the navigation happens without starting ServiceWorkers or executing JavaScript, which allows web pages to avoid performance penalties due to ServiceWorker interceptions. 

We need a developer friendly doc that explains the API surface, concept, and how to use it.

Primary contacts: @sisidovski, @yoshisatoyanagisawa

### Browser support

Chromium: [crbug.com/40241479](https://crbug.com/40241479)
Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1855580
WebKit: https://bugs.webkit.org/show_bug.cgi?id=269893

### Tasks

- [x] Currently [InstallEvent]( https://developer.mozilla.org/en-US/docs/Web/API/InstallEvent) is labelled as deprecated, we have to remove it.
- [ ] The API adds `addRoutes` function to [InstallEvent]( https://developer.mozilla.org/en-US/docs/Web/API/InstallEvent). Update the page to contain API surface and list all input options that can take.

### Dependencies

- [x] https://github.com/w3c/ServiceWorker/pull/1701
- [ ] https://github.com/whatwg/fetch/pull/1737
- [x] https://github.com/whatwg/urlpattern/pull/219

### Additional information

- Spec change: https://github.com/w3c/ServiceWorker/pull/1701
- Public explainer: https://github.com/WICG/service-worker-static-routing-api

### Are you willing to support this work?

Yes

**Comment by yoshisatoyanagisawa** [comment]
Thanks for filing the issue.
In addition to https://github.com/whatwg/urlpattern/pull/219, we will also have a dependent PR that address https://github.com/whatwg/urlpattern/issues/218.  I will work on it after https://github.com/whatwg/urlpattern/pull/219.

It might be nice if we can provide a demo page and source there, which people can just clone and try their own routes.
Something like https://googlechrome.github.io/samples/service-worker/registration-events/ or https://bncb2v.csb.app/

**Comment by bsmth** [comment]
Thanks for raising this one. I think there's been changes on this already:

- [x] https://github.com/mdn/content/pull/36274 removes the deprecated badge
- [x] https://github.com/mdn/content/pull/34555 added docs

See https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API#using_static_routing_to_control_how_resources_are_fetched

I think this covers the requirements, so I'm closing as done, but if there's anything missing, please let me know and we can update or fix it! Thank you :)
