### ISSUE TITLE
[PROJECT] Firefox release 125

### ISSUE THREAD

**Issue by pepelsbey** [mdn/mdn#532]
Project tracking issue for FF125

```[tasklist]
### Tasks
- [ ] https://github.com/mdn/content/issues/32664
- [ ] https://github.com/mdn/content/issues/32663
- [ ] https://github.com/mdn/content/issues/32662
- [ ] https://github.com/mdn/content/issues/32661
- [ ] https://github.com/mdn/content/issues/32775
- [ ] https://github.com/mdn/content/issues/32776
- [ ] https://github.com/mdn/content/issues/32777
- [ ] https://github.com/mdn/content/issues/32778
- [ ] https://github.com/mdn/content/issues/32779
- [ ] https://github.com/mdn/content/issues/32746
```

**Comment by Elchi3** [comment]
See also the features the Open Web Docs BCD Collector found for Firefox 125: https://github.com/mdn/browser-compat-data/pull/22669.

I reckon you want to add the following bugs to your list:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1811912
- https://bugzilla.mozilla.org/show_bug.cgi?id=1861201
- https://bugzilla.mozilla.org/show_bug.cgi?id=1860816
- https://bugzilla.mozilla.org/show_bug.cgi?id=1868374
- https://bugzilla.mozilla.org/show_bug.cgi?id=1880689

**Comment by Elchi3** [comment]
Firefox 125 was released yesterday and it seems it also ships canvas context loss events.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1887729 and https://www.mozilla.org/en-US/firefox/125.0.1/releasenotes/

Discovered by the @openwebdocs BCD collector with a BCD PR already submitted for review at https://github.com/mdn/browser-compat-data/pull/22852

**Comment by Elchi3** [comment]
Same for shadowrootclonable per https://bugzilla.mozilla.org/show_bug.cgi?id=1880188. See https://github.com/mdn/browser-compat-data/pull/22856 for the BCD work.

**Comment by hamishwillee** [comment]
FYI, I'll sort out https://bugzilla.mozilla.org/show_bug.cgi?id=1887729 - which is being tracked as https://github.com/mdn/content/issues/33090

I haven't looked at the other one.

**Comment by Elchi3** [comment]
fwiw, the Open Web Docs compat data collector detected that content-visibility was delayed to Firefox 125. 
The documentation project was https://github.com/mdn/content/issues/32340. 

Vinyl already updated BCD from 124 to 125 in 
https://github.com/mdn/browser-compat-data/pull/23116 and
https://github.com/mdn/browser-compat-data/pull/23115

You may want to update your release notes.

https://groups.google.com/a/mozilla.org/g/dev-platform/c/kXp-yUvkNKQ/m/ZMGZ5216AwAJ
