### ISSUE TITLE
[PROJECT] Firefox release 126

### ISSUE THREAD

**Issue by dipikabh** [mdn/mdn#537]
**Description**: Issue for tracking documentation updates for Firefox 126
[**Due Date**](https://whattrainisitnow.com/calendar/#Future_branch_dates): May 14, 2024

```[tasklist]
### Tasks
- [ ] https://github.com/mdn/content/issues/32957
- [ ] https://github.com/mdn/content/issues/33018
- [ ] https://github.com/mdn/content/issues/33080
- [ ] https://github.com/mdn/content/issues/33081
- [ ] https://github.com/mdn/content/issues/33082
- [ ] https://github.com/mdn/content/issues/33083
- [ ] https://github.com/mdn/content/issues/33084
- [ ] https://github.com/mdn/content/issues/33085
- [ ] https://github.com/mdn/content/issues/33086
- [ ] https://github.com/mdn/content/issues/33047
- [ ] https://github.com/mdn/content/issues/33089
- [ ] https://github.com/mdn/content/issues/33178
- [ ] https://github.com/mdn/content/issues/33179
- [ ] https://github.com/mdn/content/issues/33180
- [ ] https://github.com/mdn/content/issues/33220
- [ ] https://github.com/mdn/content/issues/33241
- [ ] https://github.com/mdn/content/issues/32731
```

**Comment by Elchi3** [comment]
See also the @openwebdocs BCD collector run for Firefox 126 beta at https://github.com/mdn/browser-compat-data/pull/22854.

I reckon you want to add the following bugs to your list:

- https://bugzilla.mozilla.org/show_bug.cgi?id=1880189 Element.currentCSSZoom
- https://bugzilla.mozilla.org/show_bug.cgi?id=1689705 Removed marquee elements
- https://bugzilla.mozilla.org/show_bug.cgi?id=1878143 IDBTransaction.durability
- https://bugzilla.mozilla.org/show_bug.cgi?id=1867058 Selection.direction
