### ISSUE TITLE
[PROJECT] Update docs to reflect Observatory release

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#548]
We're working on adding the Observatory tool to MDN. This checks urls and gives advise about security et al. We need to ensure MDN docs are in line with the tool.

```[tasklist]
### Tasks
- [x] New landing page
- [x] Re-org main security page
- [x] Update sidebar
- [x] General phasing approach
- [x] Review See Also links across relevant pages
- [x] Guide pages
```
