### ISSUE TITLE
Add support for WebAssembly ESM Integration

### ISSUE THREAD

**Issue by guybedford** [mdn/mdn#549]
### Proposal

The WebAssembly ESM Integration [proposal](https://github.com/webassembly/esm-integration) recently moved to Phase 3 implementation status, allowing WebAssembly modules to be imported in the JS module system. In addition, with the new [source phase imports syntax](https://github.com/tc39/proposal-source-phase-imports) allows importing WebAssembly modules in their uninstantiated phase for multi-instantiation providing a more streamlined loading experience for WebAssembly.

### Browser support

Under development in V8 and Chromium.

### Tasks

- [ ] Add a new WebAssembly `source` phase row to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules
- [ ] Update https://developer.mozilla.org/en-US/docs/WebAssembly/Loading_and_running to note the new loading mechanism for WebAssembly

### Dependencies

- [ ] HTML PR (incoming)

### Are you willing to support this work?

Yes

**Comment by chrisdavidmills** [comment]
I've done some research on this issue, and found the following useful links:

- [WebAssembly/ES Module Integration proposal](https://github.com/WebAssembly/esm-integration/blob/main/proposals/esm-integration/README.md)
- [Source phase imports ChromeStatus](https://chromestatus.com/feature/5796131906519040)
- [WebAssembly ECMAScript Module Integration ChromeStatus](https://chromestatus.com/feature/5987156463976448)

From these links, it doesn't look like these are implemented yet. I'm happy to revisit this issue when they are implemented.
