### ISSUE TITLE
[PROJECT] Firefox 128

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#553]
Tracking project for Firefox 128 release

```[tasklist]
### Tasks
- [ ] https://github.com/mdn/content/issues/33988
- [ ] https://github.com/mdn/content/issues/33980
- [ ] https://github.com/mdn/content/issues/33981
- [ ] https://github.com/mdn/content/issues/33983
- [ ] https://github.com/mdn/content/issues/33984
- [ ] https://github.com/mdn/content/issues/33985
- [ ] https://github.com/mdn/content/issues/33986
- [ ] https://github.com/mdn/content/issues/33989
- [ ] https://github.com/mdn/content/issues/33990
- [ ] https://github.com/mdn/content/issues/33991
- [ ] https://github.com/mdn/content/issues/33992
- [ ] https://github.com/mdn/content/issues/33993
- [ ] https://github.com/mdn/content/issues/33994
- [ ] https://github.com/mdn/content/issues/33995
- [ ] https://github.com/mdn/content/issues/33996
```

**Comment by Elchi3** [comment]
You probably want to add https://bugzilla.mozilla.org/show_bug.cgi?id=1890428 to your list of things shipping in Firefox 128.

The @openwebdocs BCD collector run for Firefox 128 beta is available at https://github.com/mdn/browser-compat-data/pull/23364
