### ISSUE TITLE
Remove all "@@symbol" notation

### ISSUE THREAD

**Issue by Josh-Cena** [mdn/mdn#562]
### Proposal

The spec has just removed all `@@symbol` notation (such as `@@iterator`) in favor of `%Symbol.iterator%` (the generic notation for built-in values): https://github.com/tc39/ecma262/pull/1314

Downstream PRs have been sent to WebIDL and HTML.

We should do the same for MDN. I recommend, instead of using `%Symbol.iterator%`, we just use `[Symbol.iterator]` instead. For example, ``it then looks for an [`[@@iterator]()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator) method`` would become ``it then looks for an [`[Symbol.iterator]()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator) method``. I will determine the best phrasing on a case-by-case basis.

### Browser support

/

### Tasks

- [ ] Update all BCD keys
- [ ] Update all BCD text
- [ ] Update all MDN page slugs
- [ ] Update all MDN prose
- [ ] Yari updates? Hopefully none

### Are you willing to support this work?

Yes

**Comment by Rumyra** [comment]
Hey @Josh-Cena thanks for the proposal

In regards to content I'm happy for the changes.

One of the issues with the changes in BCD is the period `.` after Symbol - we would only be able to update the descriptions and not the keys themselves with this syntax.

**Comment by Josh-Cena** [comment]
As for the BCD keys, I believe we can simply use `Array.iterator`, etc. But I'm also fine with sticking to `Array.@@iterator` just for BCD.

**Comment by Josh-Cena** [comment]
What should we do about slugs? The bad thing about `Array/Symbol.iterator` is we can no longer use jsxref such as `jsxref("Array/@@iterator"` because the macro is really dumb and would convert `jsxref("Array/Symbol.iterator"` to `jsxref("Array/Symbol/iterator"`. I would absolutely want them to be jsxref-friendly, which means either fixing jsxref or picking another convention.

**Comment by Josh-Cena** [comment]
Actually jsxref-friendliness for symbol methods is already pretty borked, due to `[Symbol.iterator]()` being treated as if it's a Markdown link, so we have to put it in a Markdown code span anyway. I would assume that `Array/Symbol.iterator` is fine.

**Comment by Josh-Cena** [comment]
Here's the wording convention that I decided on, in case we want to formalize it anywhere:

1. Say "the `[Symbol.bla]()` method" where possible.
2. Say "the `[Symbol.bla]` property" where you are specifically referring to the property, not its nature as a method, or the property is not a method (e.g. `Symbol.unscopables`). However, "an object which implements `[Symbol.iterator]()`" is also acceptable and preferred—that is, add the parentheses wherever it's not absolutely awkward to do so.
3. Don't say "the `Symbol.bla` property" as it's ambiguous whether you are referring to the `bla` property of `Symbol` or the property keyed by `Symbol.bla`.

**Comment by bsmth** [comment]
Thanks, @Josh-Cena - is this done or is there anything else left?
