### ISSUE TITLE
[PROJECT] Firefox 129

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#565]
Tracking project for FF 129 release

```[tasklist]
### Tasks
- [ ] https://github.com/mdn/content/issues/34696
- [ ] https://github.com/mdn/content/issues/34697
- [ ] https://github.com/mdn/content/issues/34698
- [ ] https://github.com/mdn/content/issues/34699
- [ ] https://github.com/mdn/content/issues/34700
- [ ] https://github.com/mdn/content/issues/34701
- [ ] https://github.com/mdn/content/issues/34702
- [ ] https://github.com/mdn/content/issues/34703
- [ ] https://github.com/mdn/content/issues/34704
- [ ] https://github.com/mdn/content/issues/34705
- [ ] https://github.com/mdn/content/issues/34706
- [ ] https://github.com/mdn/content/issues/34707
- [ ] https://github.com/mdn/content/issues/34708
```

**Comment by Elchi3** [comment]
Please find the @openwebdocs BCD collector run for Firefox 129 beta at https://github.com/mdn/browser-compat-data/pull/23730.

You probably want to add the following bugs to your list:

- https://bugzilla.mozilla.org/show_bug.cgi?id=1796785 PerformanceResourceTiming.responseStatus 
- https://bugzilla.mozilla.org/show_bug.cgi?id=1890706 Geolocation toJSON methods
