### ISSUE TITLE
Remove all unnecessary innerHTML assignments from example repos

### ISSUE THREAD

**Issue by Josh-Cena** [mdn/mdn#567]
### Proposal

After https://github.com/mdn/content/issues/13496, the content now avoids `innerHTML` where possible:

- Use `innerText` where line breaks are needed,
- `textContent` otherwise,
- and `appendChild` if necessary.

For example, here's the old way:

```js
msg.innerHTML = "";
```

Here's the new way:

```js
msg.textContent = "";
```

Here's the old way:

```js
msg.innerHTML += "Hello!<br>";
```

Here's the new way:

```js
msg.innerText += "Hello!\n";
```

Here's the old way:

```js
note.innerHTML += "<li>item</li>";
```

Here's the new way:

```js
note.appendChild(document.createElement("li")).textContent = "item";
```

### Browser support

/

### Tasks

- [ ] [mdn/beginner-html-site-scripted](https://github.com/search?q=org%3Amdn+%2F.innerHTML+.%3F%3D%2F+repo%3Amdn%2Fbeginner-html-site-scripted&type=code)
- [ ] [mdn/webaudio-examples](https://github.com/search?q=org%3Amdn+%2F.innerHTML+.%3F%3D%2F+repo%3Amdn%2Fwebaudio-examples&type=code)
- [ ] [mdn/webassembly-examples](https://github.com/search?q=org%3Amdn+%2F.innerHTML+.%3F%3D%2F+repo%3Amdn%2Fwebassembly-examples&type=code)
- [ ] [mdn/web-components-examples](https://github.com/search?q=org%3Amdn+%2F.innerHTML+.%3F%3D%2F+repo%3Amdn%2Fweb-components-examples&type=code)
- [ ] [mdn/pwa-examples](https://github.com/search?q=org%3Amdn+%2F.innerHTML+.%3F%3D%2F+repo%3Amdn%2Fpwa-examples&type=code)
- [ ] [mdn/dom-examples](https://github.com/search?q=org%3Amdn+%2F.innerHTML+.%3F%3D%2F+repo%3Amdn%2Fdom-examples&type=code)
- [ ] [mdn/interactive-examples](https://github.com/search?q=org%3Amdn+%2F.innerHTML+.%3F%3D%2F++repo%3Amdn%2Finteractive-examples&type=code)
- [ ] [mdn/learning-area](https://github.com/search?q=org%3Amdn+%2F.innerHTML+.%3F%3D%2F+repo%3Amdn%2Flearning-area&type=code)

### Dependencies

- [ ]

### Are you willing to support this work?

Maybe

**Comment by bsmth** [comment]
I think this is a good idea. We can probably cross off interactive-examples from the list. Most of the others are one or two occurrences, and the majority are in dom-examples (17) and  learning-area (30).

**Comment by arthurliraprof4-boop** [comment]
https://github.com/mdn/mdn/issues/567

**Comment by sakthivelgreen** [comment]
Hi! I'd like to help with this. I will start working on updating the files.
