### ISSUE TITLE
[PROJECT] Firefox 130

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#570]
Project tracker for Firefox 130 release updates

```[tasklist]
### Tasks
- [ ] https://github.com/mdn/content/issues/35279
- [ ] https://github.com/mdn/content/issues/35280
- [ ] https://github.com/mdn/content/issues/35281
- [ ] https://github.com/mdn/content/issues/35282
- [ ] https://github.com/mdn/content/issues/35283
- [ ] https://github.com/mdn/content/issues/35284
- [ ] https://github.com/mdn/content/issues/35285
```
