### ISSUE TITLE
[PROJECT] Firefox 132

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#585]
Project tracking for Firefox 132

```[tasklist]
### Tasks
- [ ] https://github.com/mdn/content/issues/36112
- [ ] https://github.com/mdn/content/issues/36113
- [ ] https://github.com/mdn/content/issues/36114
- [ ] https://github.com/mdn/content/issues/36115
- [ ] https://github.com/mdn/content/issues/36116
- [ ] https://github.com/mdn/content/issues/36117
- [ ] https://github.com/mdn/content/issues/36118
- [ ] https://github.com/mdn/content/issues/36119
- [ ] https://github.com/mdn/content/issues/36120
- [ ] https://github.com/mdn/content/issues/36121
- [ ] https://github.com/mdn/content/issues/36122
- [ ] https://github.com/mdn/content/issues/36123
- [ ] https://github.com/mdn/content/issues/36124
- [ ] https://github.com/mdn/content/issues/36125
- [ ] https://github.com/mdn/content/issues/36126
```
