### ISSUE TITLE
[PROJECT] Bring MDN up-to-date with WebGPU updates

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/mdn#591]
The source of these changes is @beaufortfrancois 's "What's New in WebGPU" list at https://developer.chrome.com/docs/web-platform/webgpu/news. I've chosen to omit non-standard and early-stage features from the list for now. We can tackle those later on, once they become standard and/or it is felt that MDN docs are needed.

```[tasklist]
### Tasks
- [ ] https://github.com/mdn/content/issues/36341
- [ ] https://github.com/mdn/content/issues/36342
- [ ] https://github.com/mdn/content/issues/36343
- [ ] https://github.com/mdn/content/issues/36344
- [ ] https://github.com/mdn/content/issues/36345
- [ ] https://github.com/mdn/content/issues/36346
- [ ] https://github.com/mdn/content/issues/36348
- [ ] https://github.com/mdn/content/issues/36349
- [ ] https://github.com/mdn/content/issues/36350
- [ ] https://github.com/mdn/content/issues/36352
- [ ] https://github.com/mdn/content/issues/36353
- [ ] https://github.com/mdn/content/issues/36354
- [ ] https://github.com/mdn/content/issues/36356
- [ ] https://github.com/mdn/content/issues/36358
- [ ] https://github.com/mdn/content/issues/36359
- [ ] https://github.com/mdn/content/issues/36361
- [ ] https://github.com/mdn/content/issues/36370
- [ ] https://github.com/mdn/content/issues/36371
- [ ] https://github.com/mdn/content/issues/36372
- [ ] https://github.com/mdn/content/issues/36373
- [ ] https://github.com/mdn/content/issues/36374
- [ ] https://github.com/mdn/content/issues/36375
- [ ] https://github.com/mdn/content/issues/36394
```
