### ISSUE TITLE
[PROJECT] Firefox 133

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#596]
Issues for Firefox 133 release

```[tasklist]
### Tasks
- [ ] https://github.com/mdn/content/issues/36530
- [ ] https://github.com/mdn/content/issues/36531
- [ ] https://github.com/mdn/content/issues/36532
- [ ] https://github.com/mdn/content/issues/36533
- [ ] https://github.com/mdn/content/issues/36534
- [ ] https://github.com/mdn/content/issues/36535
- [ ] https://github.com/mdn/content/issues/36536
- [ ] https://github.com/mdn/content/issues/36537
- [ ] https://github.com/mdn/content/issues/36559
- [ ] https://github.com/mdn/content/issues/36558
- [ ] https://github.com/mdn/content/issues/36547
- [ ] https://github.com/mdn/content/issues/36546
- [ ] https://github.com/mdn/content/issues/35720
```
