### ISSUE TITLE
DOMQuad

### ISSUE THREAD

**Issue by yashrajbharti** [mdn/mdn#599]
### Proposal

The [Missing widely available pages](https://github.com/openwebdocs/project/issues/214) states some of the important web api specs that lacks an MDN feature page. One of them is the DOMQuad Web API that contains web interfaces such as DOMQuad(), getBounds(), toJSON().

### Browser support

The properties are widely supported in all major browsers:
<img width="812" alt="Screenshot 2024-11-03 at 8 55 00 PM" src="https://github.com/user-attachments/assets/d6f0932c-72ff-4ae7-9250-a692913a53e7">

### Tasks

- [x] Complete the DOMQuad() constructor feature page
- [x] Complete the DOMQuad toJSON() feature page
- [x] Complete the DOMQuad getBounds() feature page

### Additional information

I am finished with the MDN feature pages and adding a GitHub issue to link with the pull request.

### Are you willing to support this work?

Yes, I am willing to support as well as I intend to complete the widely available specs documentation in the coming weeks.
