### ISSUE TITLE
[PROJECT] Firefox 134

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#603]
Tacking issue for Firefox 134 project

```[tasklist]
### Tasks
- [ ] https://github.com/mdn/content/issues/36914
- [ ] https://github.com/mdn/content/issues/36918
- [ ] https://github.com/mdn/content/issues/36917
- [ ] https://github.com/mdn/content/issues/36916
- [ ] https://github.com/mdn/content/issues/36915
- [ ] https://github.com/mdn/content/issues/36919
- [ ] https://github.com/mdn/content/issues/36920
- [ ] https://github.com/mdn/content/issues/36921
- [ ] https://github.com/mdn/content/issues/36922
```

**Comment by Elchi3** [comment]
You probably want to add https://bugzilla.mozilla.org/show_bug.cgi?id=1929590 to your list.
